// VARIABLES

const megaArtOriginals = {
  megaStand: {
    ox: 10,
    oy: 24,
    rows: [
      '..........KKK........',
      '........KKKCCK.......',
      '.......KBBBKCCK......',
      '......KBBBBBKKKK.....',
      '......KBBBBBKCCBK....',
      '.....KCBBBBBBKKBK....',
      '.....KCBBSWWWBBWK....',
      '.....KCBSWWKKSKWK....',
      '......KBSWWKKSKWK....',
      '.....KKBSSWWWSWSK....',
      '...KKCCKBSKKKKSKKK...',
      '..KBCCCCKSSSSSKCCBK..',
      '..KBBCCCCKKKKKCCBBK..',
      '.KBBBCKCCCCCCCKCBBBK.',
      '.KBBKKKCCCCCCCKKKBBK.',
      '.KBBBKKCCCCCCCKKBBBK.',
      '.KBBBKKBBBBBBBKKBBBK.',
      '..KKK.KBBBBBBBK.KKK..',
      '.....KCCBBBBCCCK.....',
      '....KBBCCCKCCCCBK....',
      '...KKBBBCK.KCBBBKK...',
      '.KKBBBBBK...KBBBBBKK.',
      'KBBBBBBBK...KBBBBBBBK',
      'KKKKKKKKK...KKKKKKKKK',
    ],
  },
  megaBlink: {
    ox: 10,
    oy: 24,
    rows: [
      '..........KKK........',
      '........KKKCCK.......',
      '.......KBBBKCCK......',
      '......KBBBBBKKKK.....',
      '......KBBBBBKCCBK....',
      '.....KCBBBBBBKKBK....',
      '.....KCBBSSSSBBSK....',
      '.....KCBSSSSSSSSK....',
      '......KBSKKKKSKKK....',
      '.....KKBSSSSSSSSK....',
      '...KKCCKBSKKKKSKKK...',
      '..KBCCCCKSSSSSKCCBK..',
      '..KBBCCCCKKKKKCCBBK..',
      '.KBBBCKCCCCCCCKCBBBK.',
      '.KBBKKKCCCCCCCKKKBBK.',
      '.KBBBKKCCCCCCCKKBBBK.',
      '.KBBBKKBBBBBBBKKBBBK.',
      '..KKK.KBBBBBBBK.KKK..',
      '.....KCCBBBBCCCK.....',
      '....KBBCCCKCCCCBK....',
      '...KKBBBCK.KCBBBKK...',
      '.KKBBBBBK...KBBBBBKK.',
      'KBBBBBBBK...KBBBBBBBK',
      'KKKKKKKKK...KKKKKKKKK',
    ],
  },
  megaStep: {
    ox: 10,
    oy: 24,
    rows: [
      '..........KKK.......',
      '........KKKCCK......',
      '.......KBBBKCCK.....',
      '......KBBBBBKKKK....',
      '......KBBBBBKCCBK...',
      '.....KCBBBBBBKKBK...',
      '.....KCBBSWWWBBWK...',
      '.....KCBSWWKKSKWK...',
      '......KBSWWKKSKWK...',
      '.....KKBSSWWWSWSK...',
      '...KKCCKBSKKKKSKKK..',
      '..KBCCCCKSSSSSKCCBK.',
      '..KBBCCCCKKKKKCCBBK.',
      '.KBBBCKCCCCCCCKCBBBK',
      '.KBBKKKCCCCCCCKKKBBK',
      '.KBBBKKCCCCCCCKKBBBK',
      '.KBBBKKBBBBBBBKKBBBK',
      '..KKK.KBBBBBBBK.KKK.',
      '.....KCCBBBBCCCK....',
      '....KBBCCCKCCCBK....',
      '...KKBBBCKKKBBBK....',
      '.KKBBBBBK.KBBBBBKK..',
      'KBBBBBBBK.KBBBBBBBK.',
      'KKKKKKKKK.KKKKKKKKK.',
    ],
  },
  megaRun1: {
    ox: 11,
    oy: 24,
    rows: [
      '.........................',
      '.........................',
      '.............KKK.........',
      '...........KKKCCK........',
      '..........KBBBKCCK.......',
      '.........KBBBBBKKKK......',
      '.........KBBBBBKCCBK.....',
      '......KKKCBBBBBBKKBK.....',
      '....KKCCKCBBSWWWBBWK.....',
      '...KBKCCKCBSWWKKSKWK.....',
      '..KBBBKCCKBSWWKKSKWK.KKK.',
      '.KBBBBKCCKBSSWWWSWSKKBBBK',
      '.KBBBK.KCCKBSKKKKSK.KBBBK',
      '.KBBBK.KCCCKSSSSSKCKKBBBK',
      '..KKK..KBCCCKKKKKCCCBBBK.',
      '....KK.KBBBCCCCCKCCBBBK..',
      '...KBBKKBBBBBBCK.KCBBK...',
      '..KBBBBKKBBCCCK...KKK....',
      '.KBBBBBCKKBCCCCK.........',
      '.KBBKBBCCCKKCCCBK........',
      '..KKKKBCCK.KBBBBK........',
      '......KKK..KBBBKKK.......',
      '..........KBBBBBBBK......',
      '..........KKKKKKKKK......',
    ],
  },
  megaRun2: {
    ox: 11,
    oy: 24,
    rows: [
      '.............KKK.........',
      '...........KKKCCK........',
      '..........KBBBKCCK.......',
      '.........KBBBBBKKKK......',
      '.........KBBBBBKCCBK.....',
      '........KCBBBBBBKKBK.....',
      '........KCBBSWWWBBWK.....',
      '.......KKCBSWWKKSKWK.....',
      '......KCCKBSWWKKSKWK.....',
      '.....KCCCKBSSWWWSWSK.....',
      '....KCCCCCKBSKKKKSK......',
      '....KCCCKCCKSSSSSK.......',
      '.....KBBBKCCKKKKKK.......',
      '.....KBBBBKKCCCCKBK......',
      '......KBBKBBKCCKBBK......',
      '.......KBBBBKBKKKK.......',
      '........KBBKBKCK.........',
      '.........KKCCKCK.........',
      '........KKCCCKK..........',
      '.......KBBBBBK...........',
      '......KBBBBBK............',
      '......KBBBKKK............',
      '.......KBBBBBK...........',
      '........KKKKKK...........',
    ],
  },
  megaRun3: {
    ox: 11,
    oy: 24,
    rows: [
      '.........................',
      '.........................',
      '.............KKK.........',
      '...........KKKCCK........',
      '..........KBBBKCCK.......',
      '.........KBBBBBKKKK......',
      '.........KBBBBBKCCBK.....',
      '........KCBBBBBBKKBK.....',
      '........KCBBSWWWBBWK.....',
      '......KKKCBSWWKKSKWK.....',
      '....KKCCCKBSWWKKSKWK.....',
      '...KBBBCCCKSSWWWSWSK.....',
      '..KBBBBCCKCCSKKKKSK......',
      '..KBBBKKKCCCCBSSSKKK.....',
      '..KBBBK.KCCCCCKKKBBBK....',
      '...KKK.KBCKBCCBBBBBBK....',
      '..KBBKKKBBCKBCBBBBBBK....',
      '.KBBBBKCBBBBKKKKKKKK.....',
      'KBBBBBCCCBBBBCCCK........',
      'KBBKBBCCCKKKCCCBBK.......',
      '.KKKKBBCK...KBBBBK.......',
      '.....KKK....KBBBKKK......',
      '...........KBBBBBBBK.....',
      '...........KKKKKKKKK.....',
    ],
  },
  megaRun4: {
    ox: 11,
    oy: 24,
    rows: [
      '.............KKK.........',
      '...........KKKCCK........',
      '..........KBBBKCCK.......',
      '.........KBBBBBKKKK......',
      '.........KBBBBBKCCBK.....',
      '........KCBBBBBBKKBK.....',
      '........KCBBSWWWBBWK.....',
      '.......KKCBSWWKKSKWK.....',
      '......KCCKBSWWKKSKWK.....',
      '.....KCCCKBSSWWWSWSK.....',
      '....KCCCCCKBSKKKKSK......',
      '....KCCCKCCKSSSSSK.......',
      '.....KBBBKCCKKKKKK.......',
      '.....KBBBBKKCCCCKBK......',
      '......KBBKBBKCCKBBK......',
      '.......KBBBBKBKKKK.......',
      '........KBBKBKCK.........',
      '.........KKCCKCK.........',
      '........KKCCCKK..........',
      '.......KBBBBBK...........',
      '......KBBBBBK............',
      '......KBBBKKK............',
      '.......KBBBBBK...........',
      '........KKKKKK...........',
    ],
  },
  megaRunShoot1: {
    ox: 11,
    oy: 24,
    rows: [
      '..............................',
      '..............................',
      '.............KKK..............',
      '...........KKKCCK.............',
      '..........KBBBKCCK............',
      '.........KBBBBBKKKK...........',
      '.........KBBBBBKCCBK..........',
      '......KKKCBBBBBBKKBK..........',
      '....KKCCKCBBSWWWBBWK..........',
      '...KBKCCKCBSWWKKSKWK...KKKK...',
      '..KBBBKCCKBSWWKKSKWKKKKBBBKKK.',
      '.KBBBBKCCKBSSWWWSWSKCCKBCCCKCK',
      '.KBBBK.KCCKBSKKKKSKCCCKBBBBKBK',
      '.KBBBK.KCCCKSSSSSKCCCCKBBBKKK.',
      '..KKK..KBCCCKKKKKBKKKK.KKKK...',
      '....KK.KBBBCCCCCK.............',
      '...KBBKKBBBBBBCK..............',
      '..KBBBBKKBBCCCK...............',
      '.KBBBBBCKKBCCCCK..............',
      '.KBBKBBCCCKKCCCBK.............',
      '..KKKKBCCK.KBBBBK.............',
      '......KKK..KBBBKKK............',
      '..........KBBBBBBBK...........',
      '..........KKKKKKKKK...........',
    ],
  },
  megaRunShoot2: {
    ox: 11,
    oy: 24,
    rows: [
      '.............KKK..............',
      '...........KKKCCK.............',
      '..........KBBBKCCK............',
      '.........KBBBBBKKKK...........',
      '.........KBBBBBKCCBK..........',
      '........KCBBBBBBKKBK..........',
      '........KCBBSWWWBBWK..........',
      '.......KKCBSWWKKSKWK...KKKK...',
      '......KCCKBSWWKKSKWKKKKBBBKKK.',
      '.....KCCCKBSSWWWSWSKCCKBCCCKCK',
      '....KCCCCCKBSKKKKSKCCCKBBBBKBK',
      '....KCCCKCCKSSSSSKCCCCKBBBKKK.',
      '.....KBBBKCCKKKKKKKKKK.KKKK...',
      '.....KBBBBKKCCCCK.............',
      '......KBBKBBKCCK..............',
      '.......KBBBBKBKK..............',
      '........KBBKBKCK..............',
      '.........KKCCKCK..............',
      '........KKCCCKK...............',
      '.......KBBBBBK................',
      '......KBBBBBK.................',
      '......KBBBKKK.................',
      '.......KBBBBBK................',
      '........KKKKKK................',
    ],
  },
  megaRunShoot3: {
    ox: 11,
    oy: 24,
    rows: [
      '..............................',
      '..............................',
      '.............KKK..............',
      '...........KKKCCK.............',
      '..........KBBBKCCK............',
      '.........KBBBBBKKKK...........',
      '.........KBBBBBKCCBK..........',
      '........KCBBBBBBKKBK..........',
      '........KCBBSWWWBBWK..........',
      '........KCBSWWKKSKWK...KKKK...',
      '.........KBSWWKKSKWKKKKBBBKKK.',
      '..........KSSWWWSWSKCCKBCCCKCK',
      '.........KCCSKKKKSKCCCKBBBBKBK',
      '........KCCCCBSSSKKKCCKBBBKKK.',
      '........KCCCCCKKKBBBKK.KKKK...',
      '...KK..KBCKBCCBBBBBBK.........',
      '..KBBKKKBBCKBCBBBBBBK.........',
      '.KBBBBKCBBBBKKKKKKKK..........',
      'KBBBBBCCCBBBBCCCK.............',
      'KBBKBBCCCKKKCCCBBK............',
      '.KKKKBBCK...KBBBBK............',
      '.....KKK....KBBBKKK...........',
      '...........KBBBBBBBK..........',
      '...........KKKKKKKKK..........',
    ],
  },
  megaRunShoot4: {
    ox: 11,
    oy: 24,
    rows: [
      '.............KKK..............',
      '...........KKKCCK.............',
      '..........KBBBKCCK............',
      '.........KBBBBBKKKK...........',
      '.........KBBBBBKCCBK..........',
      '........KCBBBBBBKKBK..........',
      '........KCBBSWWWBBWK..........',
      '.......KKCBSWWKKSKWK...KKKK...',
      '......KCCKBSWWKKSKWKKKKBBBKKK.',
      '.....KCCCKBSSWWWSWSKCCKBCCCKCK',
      '....KCCCCCKBSKKKKSKCCCKBBBBKBK',
      '....KCCCKCCKSSSSSKCCCCKBBBKKK.',
      '.....KBBBKCCKKKKKKKKKK.KKKK...',
      '.....KBBBBKKCCCCK.............',
      '......KBBKBBKCCK..............',
      '.......KBBBBKBKK..............',
      '........KBBKBKCK..............',
      '.........KKCCKCK..............',
      '........KKCCCKK...............',
      '.......KBBBBBK................',
      '......KBBBBBK.................',
      '......KBBBKKK.................',
      '.......KBBBBBK................',
      '........KKKKKK................',
    ],
  },
  megaShoot: {
    ox: 10,
    oy: 24,
    rows: [
      '..............KKK..............',
      '............KKKCCK.............',
      '...........KBBBKCCK............',
      '..........KBBBBBKKKK...........',
      '..........KBBBBBKCCBK..........',
      '.........KCBBBBBBKKBK..........',
      '.......KKKCBBSWWWBBWK..........',
      '.....KKCCKCBSWWKKSKWK..........',
      '....KCCCCCKBSWWKKSKWK...KKKK...',
      '...KBCCCCCKBSSWWWSWSKKKKBBBKKK.',
      '...KBBBCKCCKBSKKKKSKKCCKBCCCKCK',
      '...KBBBKBKCCKSSSSSKCCCCKBBBBKBK',
      '....KBBKBBKCCKKKKKCCCCCKBBBKKK.',
      '.....KBBBBKCCCCCCCKKKKK.KKKK...',
      '......KBBKCCCCCCCK.............',
      '.......KKBBCCCCCK..............',
      '........KBBBBBBBK..............',
      '.......KCBBBBBBCK..............',
      '......KCCCBBBBCCCK.............',
      '.....KBCCCCKKCCCBBK............',
      '...KKBBBCCK..KBBBBK............',
      '.KKBBBBBBK...KBBBKKK...........',
      'KBBBBBBBK...KBBBBBBBK..........',
      'KKKKKKKKK...KKKKKKKKK..........',
    ],
  },
  megaJump: {
    ox: 12,
    oy: 24,
    rows: [
      '............KKK...........',
      '..KK......KKKCCK......KK..',
      '.KBBK....KBBBKCCK....KBBK.',
      'KBBBBK..KBBBBBKKKK..KBBBBK',
      'KBBBKK..KBBBBBKCCBK.KKBBBK',
      '.KBBKBKKCBBBBBBKKBKKBKBBK.',
      '..KBBBBKCBBSWWWBBWKBBBBK..',
      '...KBBBKCBSWWKKSKWKCBBK...',
      '....KBBCKBSWWKKSKWKCCK....',
      '.....KCCKBSSWWWSWSKCK.....',
      '......KCCKBSSKKKSKCK......',
      '.......KCCKSKKKKKCK.......',
      '.......KCCCKSKKKCCK.......',
      '........KCCCCCCCCK........',
      '........KCCCCCCCCK........',
      '........KCCCCCCCCKKK......',
      '........KBBBBBBBBCCCK.....',
      '........KBBBBBBBCCCBBK....',
      '........KCCBBBBCCCBBBK....',
      '........KCCCCKKKKBBBBK....',
      '........KCCCK....KBBBBK...',
      '........KCCBK....KBBBBBK..',
      '........KBBBK....KKBBBBK..',
      '........KBBBBK.....KKKK...',
      '.........KBBBK............',
      '.........KBBBK............',
      '.........KBBBK............',
      '.........KBBBK............',
      '.........KBBBK............',
      '..........KKK.............',
    ],
  },
  megaJumpShoot: {
    ox: 12,
    oy: 24,
    rows: [
      '............KKK..............',
      '..KK......KKKCCK.............',
      '.KBBK....KBBBKCCK............',
      'KBBBBK..KBBBBBKKKK...........',
      'KBBBKK..KBBBBBKCCBK..........',
      '.KBBKBKKCBBBBBBKKBK..........',
      '..KBBBBKCBBSWWWBBWK..........',
      '...KBBBKCBSWWKKSKWK...KKKK...',
      '....KBBCKBSWWKKSKWKKKKBBBKKK.',
      '.....KCCKBSSWWWSWSKCCKBCCCKCK',
      '......KCCKBSSKKKSKCCCKBBBBKBK',
      '.......KCCKSKKKKKCCCCKBBBKKK.',
      '.......KCCCKSKKKCCKKK.KKKK...',
      '........KCCCCCCCCK...........',
      '........KCCCCCCCCK...........',
      '........KCCCCCCCCKKK.........',
      '........KBBBBBBBBCCCK........',
      '........KBBBBBBBCCCBBK.......',
      '........KCCBBBBCCCBBBK.......',
      '........KCCCCKKKKBBBBK.......',
      '........KCCCK....KBBBBK......',
      '........KCCBK....KBBBBBK.....',
      '........KBBBK....KKBBBBK.....',
      '........KBBBBK.....KKKK......',
      '.........KBBBK...............',
      '.........KBBBK...............',
      '.........KBBBK...............',
      '.........KBBBK...............',
      '.........KBBBK...............',
      '..........KKK................',
    ],
  },
  megaClimb: {
    ox: 8,
    oy: 24,
    rows: [
      '..KKK...........',
      '.KBBBK..........',
      '.KBBBKKK........',
      'KBBBKKCCKKK.....',
      'KBBKBBCCBBKK....',
      'KBBBBBCCBBBK....',
      'KCKBBBCCBBBBK...',
      'KCKBBBCCBBBCK...',
      'KCKBBBCCBBBCKKK.',
      'KCKBBBBBBBBCKBBK',
      '.KCKBBBBBBBKKBBK',
      '.KCCKBBBBBKCCBBK',
      '..KCCKKKKKCCCCBK',
      '...KCCCCCCCCCCCK',
      '..KKCCCCCCCKCCCK',
      '.KCCBBCCCCCKKCCK',
      'KCCCKBBBBBBBKKK.',
      'KCCCCKBBBBBBK...',
      'KBBBBBKBBBBCK...',
      '.KBBBBBKKCCCK...',
      '..KBBBBKKCCCBK..',
      '..KBBBK.KCCBBK..',
      '..KBBK...KBBBK..',
      '...KK...KBBBBK..',
      '........KBBBBK..',
      '........KBBBBK..',
      '.........KBBBK..',
      '..........KBBK..',
      '...........KK...',
    ],
  },
  megaClimbShoot: {
    ox: 8,
    oy: 24,
    rows: [
      '..KKK...................',
      '.KBBBKKKKK..............',
      '.KBBKCCCCCKK............',
      'KBBKCBBBBBBCK...........',
      'KBKBBBBBBBBBCK..........',
      'KBKBBBBBBBBBBK..........',
      'KCKBBCBBSWWWBK..........',
      'KCKBCCCSWWKKSK..........',
      'KCKBCCCSWWKKSK...KKKK...',
      'KCKBBCBSSWWWSKKKKBBBKKK.',
      '.KCKBBBBSKKKKCCCKBCCCKCK',
      '.KCCKBBBBSSCCCCCKBBBBKBK',
      '..KCCCCCCCCCCCCCKBBBKKK.',
      '...KCCCCCCCCCKKK.KKKK...',
      '..KKCCCCCCCCK...........',
      '.KCCBBCCCCCCK...........',
      'KCCCKBBBBBBBK...........',
      'KCCCCKBBBBBBK...........',
      'KBBBBBKBBBBCK...........',
      '.KBBBBBKKCCCK...........',
      '..KBBBBKKCCCBK..........',
      '..KBBBK.KCCBBK..........',
      '..KBBK...KBBBK..........',
      '...KK...KBBBBK..........',
      '........KBBBBK..........',
      '........KBBBBK..........',
      '.........KBBBK..........',
      '..........KBBK..........',
      '...........KK...........',
    ],
  },
  megaClimbTop: {
    ox: 8,
    oy: 22,
    rows: [
      '.......KK.......',
      '.....KKCCKK.....',
      '....KBBBBBBK....',
      '..KKCCCCCCCCKK..',
      '.KCCCCCCCCCCCCK.',
      'KBCCCCCCCCCCCCBK',
      'KBBBCBBBBBBCBBBK',
      'KBBKBBBBBBBBKBBK',
      'KBKKBBBBBBBBKKBK',
      '.KKBBBBBBBBCCCK.',
      '..KBBBBBBBCCCCBK',
      '..KCCBBBBCCCKBBK',
      '..KCCCCKKKKKBBBK',
      '..KCCCCK..KBBBKK',
      '..KCCCK...KBBBBK',
      '..KBBBK...KKKKKK',
      '..KBBBK.........',
      '..KBBBBK........',
      '..KBBBBK........',
      '...KBBBK........',
      '...KBBBK........',
      '....KKK.........',
    ],
  },
  megaHurt: {
    ox: 13,
    oy: 24,
    rows: [
      '............KKK...........',
      '..........KKKCCK..........',
      '.........KBBBKCCK.........',
      '........KBBBBBKKKK........',
      '........KBBBBBKCCBK.......',
      '.......KCBBBBBBKKBK.......',
      '.....KKKCBBSSSSBBSKKK.....',
      '...KKCCKCBSSSSSSSSKCCKK...',
      '..KBBCCCKBSSKKKSKKKCCBBK..',
      '.KBBBCCCKBSSSSSSSSKCCBBBK.',
      'KBBBBKKCCKBSSKKKSKCKKBBBBK',
      'KBBBK..KCCKSKKKKKCK..KBBBK',
      'KBBBK..KCCCKSKKKCCK..KBBBK',
      '.KKK....KCCCCCCCCK....KKK.',
      '........KCCCCCCCCK........',
      '........KCCCCCCCCKKK......',
      '........KBBBBBBBBCCCK.....',
      '........KBBBBBBBCCCBBK....',
      '........KCCBBBBCCCBBBK....',
      '.......KCCCCCKKKKBBBBK....',
      '.......KBCCCK....KBBBBK...',
      '.......KBBBBK....KBBBBBK..',
      '........KBBBBK...KKBBBBK..',
      '.........KBBBBK....KKKK...',
      '.........KBBBBK...........',
      '........KBBBBBK...........',
      '........KBBBKK............',
      '.........KKK..............',
    ],
  },
  megaSlide: {
    ox: 11,
    oy: 19,
    rows: [
      '..........KKK...............',
      '........KKKCCK...KKKK.......',
      '.......KBBBKCCK.KBBBBK......',
      '......KBBBBBKKKKBBBBBK......',
      '......KBBBBBKCCBKBBBBK......',
      '.....KCBBBBBBKKBKBBKK.......',
      '.....KCBBSWWWBBWKKK.........',
      '.....KCBSWWKKSKWK.KKK.......',
      '......KBSWWKKSKWKKCCBK......',
      '.....KKBSSWWWSWSKCCBBBKKKK..',
      '....KCCKBSSKKKSKKCCBBBKBBBK.',
      '...KCCCCKSKKKKKCBCBKBBBBBKK.',
      '..KBCCCCCKSKKKCCBCKKBBBBKK..',
      '..KBBKKBCCCCCCCBBBK.KBBKK...',
      '..KBBBKKKCCCCCCBBBK.KBKKK...',
      '..KBBBK..KCCCCBBBCKKKKKBBK..',
      '..KBBBK...KBCBBBCCCCBBBBBBK.',
      '.KBBBBBK...KKBBBCCCBBBBBBBBK',
      'KBBBKKK......KKKKKKBBBBBBBBK',
      '.KKK...............KKKKKBBBK',
      '........................KKK.',
    ],
  },
  megaBeam: {
    ox: 11,
    oy: 32,
    rows: [
      '........KCBBCK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '.......KCCBCCK........',
      '.......KCCCCCK........',
      '.......KBCBCCK........',
      '.......KBCBBCK........',
      '.......KBCBBBK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '.......KCCBCCK........',
      '.......KCCCCCK........',
      '.......KBCBCCK........',
      '.......KBCBBCK........',
      '.......KBCBBBK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '.......KCCBCCK........',
      '.......KCCCCCK........',
      '.......KBCBCCK........',
      '.......KBCBBCK........',
      '.......KBCBBBK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '........KCBBCK........',
      '.......KCCBCCK........',
      '.......KCCCCCK........',
      '.......KBCBCCK........',
      '.......KBCBBCK........',
      '.......KBCBBBK........',
    ],
  },
  megaTeleportA: {
    ox: 11,
    oy: 32,
    rows: [
      '......................',
      '......................',
      '......................',
      '......................',
      '........KKKKKK........',
      '.......KBCCCCCK.......',
      '.......CBCBBBBB.......',
      '.......CBBBCCCC.......',
      '......................',
      '......................',
      '......................',
      '......................',
      '........KKKKKK........',
      '.......KBCCCCCK.......',
      '.KKKKKKCBCBBBBBKKKKKK.',
      'KBBBBBBCBBBCCCCBBBBBBK',
      '......................',
      '......................',
      '......................',
      '......................',
      '........KKKKKK........',
      '.......KBCCCCCK.......',
      '.KKKKKKCBCBBBBBKKKKKK.',
      'KBBBBBBCBBBCCCCBBBBBBK',
      'KCBBBBCCCBBBBBBCBBBBCK',
      '.KBBBBCCBBBBBBBCBBBBK.',
      '..KKBCCCBCBBCBCCCBKK..',
      '....KCCCBCCBCCCCCK....',
      '.....KBCBCCBCCBBK.....',
      '....KBCBBCBBBBBCBK....',
      '...KBBCBBCBBBCBCBBK...',
      '....KKKKKKKKKKKKKK....',
    ],
  },
  megaTeleportB: {
    ox: 11,
    oy: 32,
    rows: [
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '......................',
      '........KKKKKK........',
      '.......KBCCCCCK.......',
      '.......CBCBBBBB.......',
      '.......CBBBCCCC.......',
      'KCBBBBCCCBBBBBBCBBBBCK',
      '.KBBBBCCBBBBBBBCBBBBK.',
      '..KKBCCCBCBBCBCCCBKK..',
      '....KCCCBCCBCCCCCK....',
      '.....KBCBCCBCCBBK.....',
      '....KBCBBCBBBBBCBK....',
      '...KBBCBBCBBBCBCBBK...',
      '....KKKKKKKKKKKKKK....',
    ],
  },
  megaWeaponGet: {
    ox: 28,
    oy: 93,
    rows: [
      '...............KKKK...............KKKKK.................',
      '..........KKKKKWWWWKKKK........KKKvBBBvK................',
      '........KKBBBBWWWWWCvvvKK.....KBBBBBBBvvK...............',
      '.......KBBBBBBWWWWWCvBBvvKK..KBBBBBBBBBvK...............',
      '......KBBCCWWBWWWWWCvBBBvvvKKKBBBBBBBBBvK...............',
      '.....KBBCCCWBBWWWWWCvBBBBvvvKBBBBBBBBBBvK...............',
      '....KBBCCCBBBBBWWWWvBBBBBvvvKBBBBBBBBBBvvK..............',
      '....KBBCCBBBBBBBBBBBBBBBBBvvvKBBBBvvBBvvvK..............',
      '...KBBCCBBBBBBBWWWWvBBBBBBvvvvKBBBBvvvvvvK..............',
      '...KBBWBBBBBBBWWWWCCvBBBBBvvvvKBBBBvvvvvK...............',
      '...KBBBBBBBBBBWWWWCCvBBBBBvvvvKKBBvvvvvvK...............',
      '..KBBBBBBBBBBBWWWWCCvBBBBvvvvvvKBBvvvvKK................',
      '..KBBBBBBBBBBBWWWWWCBBBBvvvvvvvKvvvvKK..................',
      '..KBBBBBBKKKKBBWWWCBBKKKKvvvvvvKvvKK....................',
      '..KWBBBBKSSSSKBBBBBBKSSSSKvvvvCKvK......................',
      '.KWWBBBKSSWWWWKBBBBKWWWWSSKvvvCCK.......................',
      '.KWWWBBKSWWWWWWKBBKWWWWWWSKKvCCCK.......................',
      '.KWCCBKSWWWWWKWKBBKWKWWWWWSKvCCWK.......................',
      '.KWWCBKSWWWWKWKWBBWKWKWWWWSKvCWWK.......................',
      '.KWWCBKSWWWWKKKWBBWKKKWWWWSKvCWWK.......................',
      '.KCWCBKSWWWWKKKWSSWKKKWWWWSKvCWCK.......................',
      '.KCWCBKSWWWWKKKWSSWKKKWWWWSKvCWCK.......................',
      '.KCCCBKSWWWWWKWWSSWWKWWWWWSKvCCCK.......................',
      '..KCCBKSSWWWWWWSSSSWWWWWWSSKvCCK........................',
      '...KCBBKSSWWWWSSSSSSWWWWSSKvvCK.........................',
      '....KBBKSSSSSSSSKKSSSSSSSSKvvK..........................',
      '.....KBKSSSSSSSSSSSSSSSSSSKvKK..........................',
      '.....KBKSSSSSSSSSSSSSSSSSSKvKCK.........................',
      '......KBKSSSSSSSKKKKSSSSSKvKCK..........................',
      '.....KKKBSSSSSKKKSSSKSSSSvKKCK..........................',
      '....KCCKKKSSSSSSSSSSSSSSKKCCCK..........................',
      '...KCCCCKKKKSSSSSSSSSSKKKCCCK...........................',
      '...KCCCCCCKKKKKSSSSKKKCCCCCCK...........................',
      '..KCCCCCCCCCCKKKKKKKKKKCCCCCK...........................',
      '..KCCCCCCCCKKKBBBBKBBBBKKCCCK...........................',
      '.KCCCCCCCKKBBBBBBBBBBKKBKKCCK..........KKK..............',
      '.KCCCCCKKBBBCCBBBBBBBKKKvKCCK......KKKKvvvKK............',
      '.KCCCCKKBBCCCCCBBBBBBKSKvKCCBK...KKCCCKvBBvvK...........',
      'KCCCCKBBBCCCCBBBBBBBBBKvvKCCvvK.KCCCCKvBBBBvvK..........',
      'KCCCCKBBCCCBBBBBBBvBBBBvKKCCvvvKCCCCCKBBBBBBvvK.........',
      'KCCCKBBBCBBBBBBBBBvvBBvvKCCvvvvKCCCCCKBBBBBBvvK.........',
      'KCCCKBBBBBBBBBBBBBBvvvvKKCCvvvKCCCCCKBBBBBBBvvvK........',
      'KCCKBBBBBBBBBvvBBBBvvvvKKCvvvvKCCCCCKBBBBBBBBvvK........',
      'KCCKBBBBBBBvvKKvBBBBvvKKCvvvvKCCCCCCKBBBBBBBBvvvK.......',
      '.KCKBBBBBvvKKSKvBBBvvvKCvvvvvKCCCCCCKBBBBBBBBvvvK.......',
      '.KCKBBBvvKKSSKKBBBvvvKCBBvvvvKCCCCCCKBBBBBBBBvvvK.......',
      '..KCKBBvKSSKKKBBvvvvKCBBBBvvvKCCCCCKBBBBBBBBBBvvvK......',
      '...KCKBBKKKKBBvvvvKKBBBBBBBvvKCCCCCKBBBBBBBBBBvvvK......',
      '....KKKvvvvvvvvvKKBBBBBBBBBvvKCCCCCKBBBBBBBBBBvvvK......',
      '.......KKKKKKKKKBBBBBBBBBBBvKCCCCCKKBBBBBBBBBBvvvK......',
      '...........KBBBBBBBBBBBBBBBvKCCCCK.KBBBBBBBBBBBvvvK.....',
      '...........KBBBBBBBBBBBBBBvvKCCCK..KBBBBBBBBBBBvvvK.....',
      '............KBBBBBBKKKKKvvvvKCCK...KvBBBBBBBBBBvvvK.....',
      '............KBBBBKKKCCCCKKvvKKK....KvBBBBBBBBBBvvvK.....',
      '.............KBBKKCCCCCCCCKK.......KBBBBBBBBBBBvvvK.....',
      '..............KKKCCCCCCCCCCK......KBBBBBBBBBBBvvvvvK....',
      '...............KCCCCCCCCCCCCK.....KBBBBBBBBBBvvvvvvKK...',
      '................KCCCCCCCCCCCCK.....KBBBBBBBBBBBBBBvvvK..',
      '.................KCCCCCCCCCCCCK.....KBBBBBBBBBBBBBvvvvK.',
      '.................KCCCCCCCCCCCCK.....KBBBBBBBBBBBBBBBvvK.',
      '..................KCCCCCCCCCCCCK.....KBBBBBBBBBBBBBBvvvK',
      '..................KCCCCCCCCCCCCKK.....KBBBBBBBBBBBBBBvvK',
      '...................KCCCCCCCCCCCKvK.....KBBBBBBBBBBBBBBvK',
      '....................KCCCCCCCCCCKvvKK....KKBBBBBBBBBBBBvK',
      '.....................KCCCCCCCCvKvvvvK.....KKBBBBBBBBBBBK',
      '......................KKCCCCCvvKvvvvvK......KKBBBBBBBBBK',
      '........................KKvvvvKBBBvvvvK.......KKKBBBBBK.',
      '........................KBKKKKBBBBBBvvvK.........KKKKK..',
      '........................KBBBBBBBBBBBBvvvK...............',
      '........................KBBBBBBBBBBBBBvvvK..............',
      '........................KBBBBBBBBBBBBBBvvvK.............',
      '.........................KBBBBBBBBBBBBBvvvvK............',
      '.........................KBBBBBBBBBBBBBBvvvvKK..........',
      '..........................KBBBBBBBBBBBBBvvvvvvK.........',
      '..........................KBBBBBBBBBBBBBBvvvvvvK........',
      '...........................KBBBBBBBBBBBBvvvvvvvvK.......',
      '...........................KBBBBBBBBBBBBvvvvvvvvK.......',
      '............................KBBBBBBBBBBBBBvvvvvvvK......',
      '............................KBBBBBBBBBBBBBBBvvvvvK......',
      '.............................KBBBBBBBBBBBBBBBvvvvvK.....',
      '..............................KBBBBBBBBBBBBBBBvvvvK.....',
      '...............................KBBBBBBBBBBBBBBBvvvK.....',
      '................................KBBBBBBBBBBBBBBvvvvK....',
      '.................................KBBBBBBBBBBBBBBvvvK....',
      '.................................KBBBBBBBBBBBBBBvvvK....',
      '..................................KBBBBBBBBBBBBBvvvK....',
      '..................................KBBBBBBBBBBBBBBvvK....',
      '...................................KBBBBBBBBBBBBBvvK....',
      '....................................KBBBBBBBBBBBBvK.....',
      '.....................................KBBBBBBBBBBBK......',
      '......................................KKBBBBBBBBK.......',
      '........................................KKKBBBBK........',
      '...........................................KKKK.........',
    ],
  },
  megaThrow: {
    ox: 10,
    oy: 24,
    rows: [
      '..............KKK..........',
      '............KKKCCK.........',
      '...........KBBBKCCK........',
      '..........KBBBBBKKKK.......',
      '..........KBBBBBKCCBK......',
      '.........KCBBBBBBKKBK......',
      '.......KKKCBBSWWWBBWK......',
      '.....KKCCKCBSWWKKSKWK......',
      '....KCCCCCKBSWWKKSKWK......',
      '...KBCCCCCKBSSWWWSWSK......',
      '...KBBBCKCCKBSKKKKSKK......',
      '...KBBBKBKCCKSSSSSKCCK.....',
      '....KBBKBBKCCKKKKKCCCCK....',
      '.....KBBBBKCCCCCCCCCCCCK...',
      '......KBBKCCCCCCCKKKCCBBK..',
      '.......KKBBCCCCCK...KBBBK..',
      '........KBBBBBBBK...KBBBBK.',
      '.......KCBBBBBBCK....KBBBK.',
      '......KCCCBBBBCCCK...KBBBBK',
      '.....KBCCCCKKCCCBBK..KBKBBK',
      '...KKBBBCCK..KBBBBK...K.KBK',
      '.KKBBBBBBK...KBBBKKK.....K.',
      'KBBBBBBBK...KBBBBBBBK......',
      'KKKKKKKKK...KKKKKKKKK......',
    ],
  },
  megaRunThrow1: {
    ox: 11,
    oy: 24,
    rows: [
      '.............................',
      '.............................',
      '.............KKK.............',
      '...........KKKCCK............',
      '..........KBBBKCCK...........',
      '.........KBBBBBKKKK..........',
      '.........KBBBBBKCCBK.........',
      '......KKKCBBBBBBKKBK.........',
      '....KKCCKCBBSWWWBBWK.....KKK.',
      '...KBKCCKCBSWWKKSKWK....KBKBK',
      '..KBBBKCCKBSWWKKSKWKKKKKKKBBK',
      '.KBBBBKCCKBSSWWWSWSKCCKBBBBK.',
      '.KBBBK.KCCKBSKKKKSKCCCKBBBBK.',
      '.KBBBK.KCCCKSSSSSKCCCCKBBBBK.',
      '..KKK..KBCCCKKKKKBKKKKKKKKBBK',
      '....KK.KBBBCCCCCK.........KK.',
      '...KBBKKBBBBBBCK.............',
      '..KBBBBKKBBCCCK..............',
      '.KBBBBBCKKBCCCCK.............',
      '.KBBKBBCCCKKCCCBK............',
      '..KKKKBCCK.KBBBBK............',
      '......KKK..KBBBKKK...........',
      '..........KBBBBBBBK..........',
      '..........KKKKKKKKK..........',
    ],
  },
  megaRunThrow2: {
    ox: 11,
    oy: 24,
    rows: [
      '.............KKK.............',
      '...........KKKCCK............',
      '..........KBBBKCCK...........',
      '.........KBBBBBKKKK..........',
      '.........KBBBBBKCCBK.........',
      '........KCBBBBBBKKBK.........',
      '........KCBBSWWWBBWK.....KKK.',
      '.......KKCBSWWKKSKWK....KBKBK',
      '......KCCKBSWWKKSKWKKKKKKKBBK',
      '.....KCCCKBSSWWWSWSKCCKBBBBK.',
      '....KCCCCCKBSKKKKSKCCCKBBBBK.',
      '....KCCCKCCKSSSSSKCCCCKBBBBK.',
      '.....KBBBKCCKKKKKKKKKKKKKKBBK',
      '.....KBBBBKKCCCCK.........KK.',
      '......KBBKBBKCCK.............',
      '.......KBBBBKBKK.............',
      '........KBBKBKCK.............',
      '.........KKCCKCK.............',
      '........KKCCCKK..............',
      '.......KBBBBBK...............',
      '......KBBBBBK................',
      '......KBBBKKK................',
      '.......KBBBBBK...............',
      '........KKKKKK...............',
    ],
  },
  megaRunThrow3: {
    ox: 11,
    oy: 24,
    rows: [
      '.............................',
      '.............................',
      '.............KKK.............',
      '...........KKKCCK............',
      '..........KBBBKCCK...........',
      '.........KBBBBBKKKK..........',
      '.........KBBBBBKCCBK.........',
      '........KCBBBBBBKKBK.........',
      '........KCBBSWWWBBWK.....KKK.',
      '........KCBSWWKKSKWK....KBKBK',
      '.........KBSWWKKSKWKKKKKKKBBK',
      '..........KSSWWWSWSKCCKBBBBK.',
      '.........KCCSKKKKSKCCCKBBBBK.',
      '........KCCCCBSSSKKKCCKBBBBK.',
      '........KCCCCCKKKBBBKKKKKKBBK',
      '...KK..KBCKBCCBBBBBBK.....KK.',
      '..KBBKKKBBCKBCBBBBBBK........',
      '.KBBBBKCBBBBKKKKKKKK.........',
      'KBBBBBCCCBBBBCCCK............',
      'KBBKBBCCCKKKCCCBBK...........',
      '.KKKKBBCK...KBBBBK...........',
      '.....KKK....KBBBKKK..........',
      '...........KBBBBBBBK.........',
      '...........KKKKKKKKK.........',
    ],
  },
  megaRunThrow4: {
    ox: 11,
    oy: 24,
    rows: [
      '.............KKK.............',
      '...........KKKCCK............',
      '..........KBBBKCCK...........',
      '.........KBBBBBKKKK..........',
      '.........KBBBBBKCCBK.........',
      '........KCBBBBBBKKBK.........',
      '........KCBBSWWWBBWK.....KKK.',
      '.......KKCBSWWKKSKWK....KBKBK',
      '......KCCKBSWWKKSKWKKKKKKKBBK',
      '.....KCCCKBSSWWWSWSKCCKBBBBK.',
      '....KCCCCCKBSKKKKSKCCCKBBBBK.',
      '....KCCCKCCKSSSSSKCCCCKBBBBK.',
      '.....KBBBKCCKKKKKKKKKKKKKKBBK',
      '.....KBBBBKKCCCCK.........KK.',
      '......KBBKBBKCCK.............',
      '.......KBBBBKBKK.............',
      '........KBBKBKCK.............',
      '.........KKCCKCK.............',
      '........KKCCCKK..............',
      '.......KBBBBBK...............',
      '......KBBBBBK................',
      '......KBBBKKK................',
      '.......KBBBBBK...............',
      '........KKKKKK...............',
    ],
  },
  megaJumpThrow: {
    ox: 12,
    oy: 24,
    rows: [
      '............KKK.............',
      '..KK......KKKCCK............',
      '.KBBK....KBBBKCCK...........',
      'KBBBBK..KBBBBBKKKK..........',
      'KBBBKK..KBBBBBKCCBK.........',
      '.KBBKBKKCBBBBBBKKBK.........',
      '..KBBBBKCBBSWWWBBWK.....KKK.',
      '...KBBBKCBSWWKKSKWK....KBKBK',
      '....KBBCKBSWWKKSKWKKKKKKKBBK',
      '.....KCCKBSSWWWSWSKCCKBBBBK.',
      '......KCCKBSSKKKSKCCCKBBBBK.',
      '.......KCCKSKKKKKCCCCKBBBBK.',
      '.......KCCCKSKKKCCKKKKKKKBBK',
      '........KCCCCCCCCK.......KK.',
      '........KCCCCCCCCK..........',
      '........KCCCCCCCCKKK........',
      '........KBBBBBBBBCCCK.......',
      '........KBBBBBBBCCCBBK......',
      '........KCCBBBBCCCBBBK......',
      '........KCCCCKKKKBBBBK......',
      '........KCCCK....KBBBBK.....',
      '........KCCBK....KBBBBBK....',
      '........KBBBK....KKBBBBK....',
      '........KBBBBK.....KKKK.....',
      '.........KBBBK..............',
      '.........KBBBK..............',
      '.........KBBBK..............',
      '.........KBBBK..............',
      '.........KBBBK..............',
      '..........KKK...............',
    ],
  },
  megaClimbThrow: {
    ox: 8,
    oy: 24,
    rows: [
      '..KKK..................',
      '.KBBBKKKKK.............',
      '.KBBKCCCCCKK...........',
      'KBBKCBBBBBBCK..........',
      'KBKBBBBBBBBBCK.........',
      'KBKBBBBBBBBBBK.........',
      'KCKBBCBBSWWWBK.........',
      'KCKBCCCSWWKKSK......KK.',
      'KCKBCCCSWWKKSK.....KBBK',
      'KCKBBCBSSWWWSKKKKKKBBK.',
      '.KCKBBBBSKKKKCCCBBBBBK.',
      '.KCCKBBBBSSCCCCCBBBBBK.',
      '..KCCCCCCCCCCCCCBBBBBK.',
      '...KCCCCCCCCCKKKKKKKK..',
      '..KKCCCCCCCCK..........',
      '.KCCBBCCCCCCK..........',
      'KCCCKBBBBBBBK..........',
      'KCCCCKBBBBBBK..........',
      'KBBBBBKBBBBCK..........',
      '.KBBBBBKKCCCK..........',
      '..KBBBBKKCCCBK.........',
      '..KBBBK.KCCBBK.........',
      '..KBBK...KBBBK.........',
      '...KK...KBBBBK.........',
      '........KBBBBK.........',
      '........KBBBBK.........',
      '.........KBBBK.........',
      '..........KBBK.........',
      '...........KK..........',
    ],
  },
};

const effectArtOriginals = {
  megaSweat1: {
    ox: 2,
    oy: 4,
    rows: [
      '.....',
      '.....',
      'W.W..',
      '..W.W',
      'W.W.W',
      'WW.WW',
      '.WWWW',
      '.WWW.',
    ],
  },
  megaSweat2: {
    ox: 2,
    oy: 4,
    rows: [
      '.....',
      'W.W..',
      '..W.W',
      'W.W..',
      '.W.WW',
      '..W..',
      '.....',
      '.....',
    ],
  },
  megaSweat3: {
    ox: 2,
    oy: 4,
    rows: [
      'W.W..',
      '....W',
      '.....',
      '.W...',
      '.....',
      '.....',
      '.....',
      '.....',
    ],
  },
  megaHitStar: {
    ox: 12,
    oy: 12,
    rows: [
      '........W......W........',
      '........W.....WW........',
      '...W...WWW...WWWW...W...',
      '...WW..WWWW.WWWWW..WW...',
      '...WWW.WWWWWWWWWW.WWW...',
      '...WWWWWWWWWWWWWWWWWW...',
      'WWWWWWWWWWWWWWWWWWWWWWWW',
      '.WWWWWWWWWWWWWWWWWWWWWW.',
      '..WWWWWWWWWWWWWWWWWWWW..',
      '...WWWWWWWWWWWWWWWWWW...',
      '..WWWWWWWWWWWWWWWWWWWW..',
      '...WWWWWWWWWWWWWWWWWW...',
      '..WWWWWWWWWWWWWWWWWWWW..',
      'WWWWWWWWWWWWWWWWWWWWWWWW',
      '..WWWWWWWWWWWWWWWWWWWW..',
      '...WWWWWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWW.....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '...WWWWWWWWWWWWWWWWWW...',
      '..WWW.WWWWW.WWWWWW.WWW..',
      '.WW....WWW...WWWW....WW.',
      '.......WW.....WWW.......',
      '........W......W........',
    ],
  },
  busterShot: {
    ox: 4,
    oy: 3,
    rows: [
      '..KKKK..',
      '.KSSSSK.',
      'KSSSWWSK',
      'KSSSSWSK',
      '.KSSSSK.',
      '..KKKK..',
    ],
  },
  chargeMid1: {
    ox: 6,
    oy: 4,
    rows: [
      '.....SSSS...',
      '...SWWWWWWS.',
      '..SWWWWWWWWS',
      'SSWWWWWWWWWW',
      'SSWWWWWWWWWW',
      '..SWWWWWWWWS',
      '...SWWWWWWS.',
      '.....SSSS...',
    ],
  },
  chargeMid2: {
    ox: 6,
    oy: 4,
    rows: [
      '............',
      '.....SWWWS..',
      '...SWWWWWWS.',
      '.SWWWWWWWWW.',
      '.SWWWWWWWWW.',
      '...SWWWWWWS.',
      '.....SWWWS..',
      '............',
    ],
  },
  chargeFull1: {
    ox: 14,
    oy: 10,
    rows: [
      '........SWWS................',
      '.......WWWWWS...............',
      '......WWWS..................',
      '.....SWWS..SWWWS............',
      '.....WWWjSWWWWWWWS..........',
      '....SWWSWWWWWWWWWWW.........',
      '....WWWWWWWWWWWWWWWS........',
      '....WWWWWWWWWWWWWWWW........',
      '..SWWWWWWWWWWWWWWWWWS.......',
      'SWWWWWWWWWWWWWWWWWWWS.......',
      'SWWWWWWWWWWWWWWWWWWWS.......',
      '..SWWWWWWWWWWWWWWWWWS.......',
      '....WWWWWWWWWWWWWWWW........',
      '....WWWWWWWWWWWWWWWS........',
      '....SWWSWWWWWWWWWWW.........',
      '.....WWWjSWWWWWWWS..........',
      '.....SWWS..SWWWS............',
      '......WWWS..................',
      '.......WWWWWS...............',
      '........SWWS................',
    ],
  },
  chargeFull2: {
    ox: 14,
    oy: 10,
    rows: [
      '............................',
      '............................',
      '.....SWS....................',
      '....WWWWS...................',
      '...WWW..SS....SSS...........',
      '..SWWS...S..SWWWWWS.........',
      '..WWW......SWWWWWWWS........',
      '.SWWS.....SWWWWWWWWW........',
      '.SWW....SWWWWWWWWWWWS.......',
      '.WWW...SWWWWWWWWWWWWS.......',
      '.WWW...SWWWWWWWWWWWWS.......',
      '.SWW....SWWWWWWWWWWWS.......',
      '.SWWS.....SWWWWWWWWW........',
      '..WWW......SWWWWWWWS........',
      '..SWWS...S..SWWWWWS.........',
      '...WWW..SS....SSS...........',
      '....WWWWS...................',
      '.....SWS....................',
      '............................',
      '............................',
    ],
  },
  chargeFull3: {
    ox: 14,
    oy: 10,
    rows: [
      '............................',
      '............................',
      '............................',
      '..................BCCCB.....',
      '....SWS.........BCCCCCCCB...',
      '...WWWWW........CCCCCCCCCB..',
      '..SWWS.WS.....BCCCCCCCCCCCB.',
      '..WWS...W....BCCCCCCCCCCCCB.',
      '.SWW........BCCCCCCCCCCCCCCB',
      '.WWW........CCCCCCCCCCCCCCCB',
      '.WWW........CCCCCCCCCCCCCCCB',
      '.SWW........BCCCCCCCCCCCCCCB',
      '..WWS...W....BCCCCCCCCCCCCB.',
      '..SWWS.WS.....BCCCCCCCCCCCB.',
      '...WWWWW........CCCCCCCCCB..',
      '....SWS.........BCCCCCCCB...',
      '..................BCCCB.....',
      '............................',
      '............................',
      '............................',
    ],
  },
  chargeFull4: {
    ox: 14,
    oy: 10,
    rows: [
      '............................',
      '............................',
      '............................',
      '............................',
      '............................',
      '............................',
      '............................',
      '..................SWWWS.....',
      '................SWWWWWWS....',
      '..............SWWWWWWWWW....',
      '..............SWWWWWWWWW....',
      '................SWWWWWWS....',
      '..................SWWWS.....',
      '............................',
      '............................',
      '............................',
      '............................',
      '............................',
      '............................',
      '............................',
    ],
  },
  explode1: {
    ox: 12,
    oy: 12,
    rows: [
      '........WWWWWWWW........',
      '......WWWWWWWWWWWW......',
      '....WWWWW......WWWWW....',
      '...WWWW..........WWWW...',
      '..WWW..............WWW..',
      '..WW................WW..',
      '.WWW................WWW.',
      '.WW..................WW.',
      'WWW..................WWW',
      'WW....................WW',
      'WW....................WW',
      'WW....................WW',
      'WW....................WW',
      'WW....................WW',
      'WW....................WW',
      'WWW..................WWW',
      '.WW..................WW.',
      '.WWW................WWW.',
      '..WW................WW..',
      '..WWW..............WWW..',
      '...WWWW..........WWWW...',
      '....WWWWW......WWWWW....',
      '......WWWWWWWWWWWW......',
      '........WWWWWWWW........',
    ],
  },
  explode2: {
    ox: 12,
    oy: 12,
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.........WWWWWW.........',
      '.......WWWWWWWWWW.......',
      '.....WWWWWWWWWWWWW......',
      '.....WWWWWWWWWWWWWW.....',
      '.....WWWWWWWWWWWWWW.....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWW.....',
      '.....WWWWWWWWWWWWWW.....',
      '......WWWWWWWWWWWW......',
      '.......WWWWWWWWWW.......',
      '.........WWWWWW.........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  explode3: {
    ox: 12,
    oy: 12,
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '..........SSSS..........',
      '........SSSSSSSS........',
      '.......SSSWWWWSSS.......',
      '.......SSWWWWWWSS.......',
      '......SSWWWWWWWWSS......',
      '......SSWWWWWWWWSS......',
      '......SSWWWWWWWWSS......',
      '......SSWWWWWWWWSS......',
      '.......SSWWWWWWSS.......',
      '.......SSSWWWWSSS.......',
      '........SSSSSSSS........',
      '..........SSSS..........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  explode4: {
    ox: 12,
    oy: 12,
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '..........SSSS..........',
      '........SSSSSSSS........',
      '........SSSSSSSS........',
      '.......SSSSWWSSSS.......',
      '.......SSSWWWWSSS.......',
      '.......SSSWWWWSSS.......',
      '.......SSSSWWSSSS.......',
      '........SSSSSSSS........',
      '........SSSSSSSS........',
      '..........SSSS..........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  explode5: {
    ox: 12,
    oy: 12,
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '...........SS...........',
      '..........SSSS..........',
      '..........SSSS..........',
      '...........SS...........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  hitSpark: {
    ox: 12,
    oy: 12,
    rows: [
      '........W......W........',
      '........WW.....W........',
      '...W...WWWW...WWW...W...',
      '...WW..WWWWW.WWWW..WW...',
      '...WWW.WWWWWWWWWW.WWW...',
      '...WWWWWWWWWWWWWWWWWW...',
      'WWWWWWWWWWWWWWWWWWWWWWWW',
      '.WWWWWWWWWWWWWWWWWWWWWW.',
      '..WWWWWWWWWWWWWWWWWWWW..',
      '...WWWWWWWWWWWWWWWWWW...',
      '..WWWWWWWWWWWWWWWWWWWW..',
      '...WWWWWWWWWWWWWWWWWW...',
      '..WWWWWWWWWWWWWWWWWWWW..',
      'WWWWWWWWWWWWWWWWWWWWWWWW',
      '..WWWWWWWWWWWWWWWWWWWW..',
      '...WWWWWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWW.....',
      '....WWWWWWWWWWWWWWWW....',
      '....WWWWWWWWWWWWWWWW....',
      '...WWWWWWWWWWWWWWWWWW...',
      '..WWW.WWWWWW.WWWWW.WWW..',
      '.WW....WWWW...WWW....WW.',
      '.......WWW.....WW.......',
      '........W......W........',
    ],
  },
  dust1: {
    ox: 4,
    oy: 8,
    rows: [
      '....WS..',
      '.SW.WWW.',
      '.WWWW.WS',
      'W.SW.S.W',
      'W..S..WW',
      'SWS.WWWS',
      '.WWWW.W.',
      '..SW..SW',
    ],
  },
  dust2: {
    ox: 4,
    oy: 8,
    rows: [
      '........',
      '....WW..',
      '.S......',
      '.W..W.S.',
      '.W..WW..',
      '..S..W..',
      '......S.',
      '........',
    ],
  },
  dust3: {
    ox: 4,
    oy: 8,
    rows: [
      '.WW.....',
      '...S....',
      'W.......',
      '.S......',
      '........',
      'W.......',
      '........',
      '........',
    ],
  },
  orbBig1: {
    ox: 6,
    oy: 6,
    rows: [
      '....CCCC....',
      '..CCCCCCCC..',
      '.CCCWWWWCCC.',
      '.CCWWWWWWCC.',
      'CCWWWWWWWWCC',
      'CCWWWWWWWWCC',
      'CCWWWWWWWWCC',
      'CCWWWWWWWWCC',
      '.CCWWWWWWCC.',
      '.CCCWWWWCCC.',
      '..CCCCCCCC..',
      '....CCCC....',
    ],
  },
  orbBig2: {
    ox: 8,
    oy: 8,
    rows: [
      '.....WWWWWW.....',
      '...WWWWWWWWWW...',
      '..WWWWWWWWWWWW..',
      '.WWWWWWWWWWWWWW.',
      '.WWWWWWWWWWWWWW.',
      'WWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWW',
      '.WWWWWWWWWWWWWW.',
      '.WWWWWWWWWWWWWW.',
      '..WWWWWWWWWWWW..',
      '...WWWWWWWWWW...',
      '.....WWWWWW.....',
    ],
  },
  orbSmall: {
    ox: 5,
    oy: 5,
    rows: [
      '...CCCC...',
      '.CCCCCCCC.',
      '.CCCCCCCC.',
      'CCCCWWCCCC',
      'CCCWWWWCCC',
      'CCCWWWWCCC',
      'CCCCWWCCCC',
      '.CCCCCCCC.',
      '.CCCCCCCC.',
      '...CCCC...',
    ],
  },
};

const itemArtOriginals = {
  energyBig1: {
    ox: 8,
    oy: 16,
    rows: [
      '.....KKKKKK.....',
      '...KKWWWWWWKK...',
      '..KWWKKKKKKWWK..',
      '.KWWKKKKKKKKWWK.',
      '.KWKKKSSSSKKKWK.',
      'KWKKKSWWSSSKKKWK',
      'KWKKSWWWSSSSKKWK',
      'KWKKSWWSSSSSKKWK',
      'KWKKSSSSSSSSKKWK',
      'KWKKSSSSSSSSKKWK',
      'KWKKKSSSSSSKKKWK',
      'KKWKKKSSSSKKKWK.',
      '.KWWKKKKKKKKWWK.',
      '..KWWKKKKKKWWK..',
      '...KKWWWWWWKK...',
      '.....KKKKKK.....',
    ],
  },
  energyBig2: {
    ox: 8,
    oy: 16,
    rows: [
      '.....KKKKKK.....',
      '...KKSSSSSSKK...',
      '..KSSKKKKKKSSK..',
      '.KSSKKKKKKKKSSK.',
      '.KSKKKKKKKKKKSKK',
      'KSKKKKKKKKKKKKSK',
      'KSKKKKKKKKKKKKSK',
      'KSKKKKKKKKKKKKSK',
      'KSKKKKKKKKKKKKSK',
      'KSKKKKKKKKKKKKSK',
      'KSKKKKKKKKKKKKSK',
      'KKSKKKKKKKKKKSK.',
      '.KSSKKKKKKKKSSK.',
      '..KSSKKKKKKSSK..',
      '...KKSSSSSSKK...',
      '.....KKKKKK.....',
    ],
  },
  oneUp: {
    ox: 8,
    oy: 16,
    rows: [
      '......KKKK......',
      '....KKKCCKKK....',
      '...KBBBCCBBBK...',
      '..KBBBBCCBBBBK..',
      '.KBBBBBKKBBBBBK.',
      '.KBBBBBCCBBBBBK.',
      '.KBBBBBCCBBBBBK.',
      'KWKKWWKKKKWWKKWK',
      'KWKWWWWKKWWWWKWK',
      'KWKWWKKWWKKWWKWK',
      'KWKSWKKWWKKWSKWK',
      '.KKSSSSSSSSSSKK.',
      '..KSSKKKKKKSSK..',
      '...KSSKKKKSSK...',
      '....KKSSSSKK....',
      '......KKKK......',
    ],
  },
  energySmall1: {
    ox: 4,
    oy: 8,
    rows: [
      '..KKKK..',
      '.KSSSSK.',
      'KSSWWSSK',
      'KSWWSSSK',
      'KSWSSSSK',
      'KSSSSSSK',
      '.KSSSSK.',
      '..KKKK..',
    ],
  },
  energySmall2: {
    ox: 4,
    oy: 8,
    rows: [
      '..KKKK..',
      '.KKKKKK.',
      'KKKKKKKK',
      'KKKKKKKK',
      'KKKKKKKK',
      'KKKKKKKK',
      '.KKKKKK.',
      '..KKKK..',
    ],
  },
  weaponEnergyBig1: {
    ox: 8,
    oy: 12,
    rows: [
      '...KKKKKKKKKK...',
      '..KCCCCCCCCCCK..',
      '.KCKKKKKKKKKKCK.',
      '.KKKKKBBBBKKKKK.',
      'KBBKKBBBBBBKKBBK',
      'KCBKKBBBBBBKKBCK',
      'KCBKKBBBBBBKKBCK',
      'KBBKKBBBBBBKKBBK',
      '.KKKKKBBBBKKKKK.',
      '.KCKKKKKKKKKKCK.',
      '..KCCCCCCCCCCK..',
      '...KKKKKKKKKK...',
    ],
  },
  weaponEnergyBig2: {
    ox: 8,
    oy: 12,
    rows: [
      '...KKKKKKKKKK...',
      '..KBBBBBBBBBBK..',
      '.KBKKKKKKKKKKBK.',
      '.KKKKKCCCCKKKKK.',
      'KBBKKCCCCCCKKBBK',
      'KCBKKCCCCCCKKBCK',
      'KCBKKCCCCCCKKBCK',
      'KBBKKCCCCCCKKBBK',
      '.KKKKKCCCCKKKKK.',
      '.KBKKKKKKKKKKBK.',
      '..KBBBBBBBBBBK..',
      '...KKKKKKKKKK...',
    ],
  },
  weaponEnergySmall1: {
    ox: 4,
    oy: 8,
    rows: [
      '..KKKK..',
      '.KCCCCK.',
      'KKKKKKKK',
      'KBKCBKBK',
      'KBKBBKBK',
      'KKKKKKKK',
      '.KCCCCK.',
      '..KKKK..',
    ],
  },
  weaponEnergySmall2: {
    ox: 4,
    oy: 8,
    rows: [
      '..KKKK..',
      '.KBBBBK.',
      'KKKKKKKK',
      'KBKCCKBK',
      'KBKCCKBK',
      'KKKKKKKK',
      '.KBBBBK.',
      '..KKKK..',
    ],
  },
};

const enemyArtOriginals = {
  metHide: {
    ox: 9,
    oy: 11,
    rows: [
      '......KKKKKK......',
      '....KKOOOOOOKK....',
      '...KOOOOOOOOOOK...',
      '..KOOOOOOOOOOOOK..',
      '..KOOOOOOOOOOOOK..',
      '.KOOOOOOOOOKOOOOK.',
      '.KKKKKKKKOKKKOKKK.',
      '.KOOOOOOOOOKOOOOK.',
      '.KOOOOOOOOOOOOOOK.',
      'KOOOOOOOOOOOOOOOOK',
      'KKKKKKKKKKKKKKKKKK',
    ],
  },
  metOpen: {
    ox: 9,
    oy: 15,
    rows: [
      '......KKKKK.......',
      '....KKOOOOOKK.....',
      '...KOOOOOOOOOK....',
      '..KOOOOOOKKOOOKKK.',
      '.KOOOOOOOKKOOOOOK.',
      '.KOOOOOKOOOOOOOK..',
      'KOOOOOKOOOOOOKK...',
      'KOOOOKOOOOOKKKK...',
      'KOOOKOOOOKKKKOOK..',
      'KOOKOOOKKOOKOOOOK.',
      'KOKOOKKKKKKKKKKKK.',
      '.KOOKKWWKKWKWKKWK.',
      '.KOKKKWWWWWKWWWWK.',
      'KOKKKKKWWWKKKWWKKK',
      'KKKKKKKKKKKKKKKKKK',
    ],
  },
  enemyShot: {
    ox: 3,
    oy: 3,
    rows: [
      '..OO..',
      '.OWWO.',
      'OWWWWO',
      'OWWWWO',
      '.OWWO.',
      '..OO..',
    ],
  },
  beakShot: {
    ox: 3,
    oy: 3,
    rows: [
      '..pp..',
      '.pWWp.',
      'pWWWWp',
      'pWWWWp',
      '.pWWp.',
      '..pp..',
    ],
  },
  screw0: {
    ox: 8,
    oy: 8,
    rows: [
      '...KKKKKKKKKK...',
      '..KpWppKKppppK..',
      '.KKKppKKKKppKKK.',
      'KpWKKpKWpKpKKWpK',
      'KppKKpKppKpKKppK',
      '.KKKppKKKKppKKK.',
      '..KppppKKppppK..',
      '...KKKKKKKKKK...',
    ],
  },
  screw1: {
    ox: 8,
    oy: 12,
    rows: [
      '...KKKKKKKKKK...',
      '..KpWppKKppppK..',
      '.KKKppKKKKppKKK.',
      'KpWKKpKWpKpKKWpK',
      'KppKKpKppKpKKppK',
      '.KKKppKKKKppKKK.',
      '..KppppKKppppK..',
      '...KKKKKKKKKK...',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '.....KKKKKK.....',
    ],
  },
  screw2: {
    ox: 8,
    oy: 16,
    rows: [
      '...KKKKKKKKKK...',
      '..KpKWpppKKppK..',
      '.KpKKKppKKKKpKK.',
      '.KKpWKppKWpKpKpK',
      '.KKppKppKppKpKpK',
      '.KpKKKppKKKKpKK.',
      '..KpKppppKKppK..',
      '...KKKKKKKKKK...',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '.....KKKKKK.....',
    ],
  },
  screw3: {
    ox: 8,
    oy: 16,
    rows: [
      '...KKKKKKKKKK...',
      '..KpWppKKppppK..',
      '.KKKppKKKKppKKK.',
      'KpWKKpKWpKpKKWpK',
      'KppKKpKppKpKKppK',
      '.KKKppKKKKppKKK.',
      '..KppppKKppppK..',
      '...KKKKKKKKKK...',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '.....KKKKKK.....',
    ],
  },
  screw4: {
    ox: 8,
    oy: 16,
    rows: [
      '...KKKKKKKKKK...',
      '..KpWKKppppKpK..',
      '.KKpKKKKppKKKpK.',
      'KpKpKpWKppKpWKK.',
      'KpKpKppKppKppKK.',
      '.KKpKKKKppKKKpK.',
      '..KppKKppppKpK..',
      '...KKKKKKKKKK...',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '......KKKK......',
      '.....KpWppK.....',
      '.....KKKKKK.....',
    ],
  },
  beak0: {
    ox: 0,
    oy: 8,
    rows: [
      'KKKKK...........',
      'KppppKK.........',
      'KppppppK........',
      'KpppWWpK........',
      'KppppWWpK.......',
      'KKppppppK.......',
      'KpKpppppK.......',
      'KpWKKKKK........',
      'KppKWWWWK.......',
      'KpKpppppK.......',
      'KKppppppK.......',
      'KpppppppK.......',
      'KppppppK........',
      'KppppppK........',
      'KppppKK.........',
      'KKKKK...........',
    ],
  },
  beak1: {
    ox: 0,
    oy: 8,
    rows: [
      'KKKKK...........',
      'KppppKK.........',
      'KpppWppK........',
      'KpppppKK........',
      'KpppKK..........',
      'KKKK............',
      'KpKKKKK.........',
      'KpWKWKWK........',
      'KppKpKpK........',
      'KpKKKKK.........',
      'KKKK............',
      'KpppKK..........',
      'KpppppKK........',
      'KppppppK........',
      'KppppKK.........',
      'KKKKK...........',
    ],
  },
  beak2: {
    ox: 0,
    oy: 8,
    rows: [
      'KKKKK...........',
      'KppppK..........',
      'KpppK...........',
      'KppK............',
      'KpK.............',
      'KK..............',
      'KpKKKKKK........',
      'KpWKKWKWK.......',
      'KppKKpKpK.......',
      'KpKKKKKK........',
      'KK..............',
      'KpK.............',
      'KppK............',
      'KpppK...........',
      'KppppK..........',
      'KKKKK...........',
    ],
  },
  beak3: {
    ox: 0,
    oy: 8,
    rows: [
      'KKK.............',
      'KppK............',
      'KpK.............',
      'KpK.............',
      'KK..............',
      'KK..............',
      'KpKKKKKKKKKKKK..',
      'KpWKKWKWKWKWKWK.',
      'KppKKpKpKpKpKpK.',
      'KpKKKKKKKKKKKK..',
      'KK..............',
      'KK..............',
      'KpK.............',
      'KpK.............',
      'KppK............',
      'KKK.............',
    ],
  },
  bigEye0: {
    ox: 16,
    oy: 40,
    rows: [
      '................KKKKKK..........',
      '......KKKKKKK.KKBBBBBBKKKKKKK...',
      '.....KBBBBBBBKBBBBBBBBBBKBBBBK..',
      '....KBBBWWWBKKKBBBBKKKKKBKWBKKK.',
      '...KBBBBBBBKKBKKBKKWWWWWKBBKKBKK',
      '...KBBBBBBBKKBWKKWWWWKKWWKBKKBWK',
      '...KBBBBBBBKKBKKWWWWKBWKWKBKKBKK',
      '..KKBBBBBBBBKKKKWWWWKBBKWKBBKKK.',
      '.KWBKBBBBBBBBKKBKWWWWKKWKBKBBK..',
      'KWBK.KKKKKKKKKKKKKWWWWWWKKBKKWK.',
      'KWK...KKBWKKKKKKKKKKKKKKKKKBKKWK',
      'KWK....KBBWKBKKKKKKKKKKKWKKBBKWK',
      'KWK....KKKKKBBKKKKKKKKKKKWKKBKWK',
      'KWK....KBBBBBBBKKKKKKKKKKWKKBBK.',
      'KBWKKKKKKBBBBBBBKKKKKKKKKKKKBBK.',
      '.KBWWWWBKKBBBBBBBKKKKKKKKKKBBWBK',
      '..KKBBBBKKBBBBBBBBBKKKKKKKBBBWBK',
      '....KKKKKBBBBBBBBBBBBBBBBBBBBWBK',
      '......KBBBBBBBBBBKWBBBBBBKWBWWBK',
      '......KBBBBBBBBBBKKBBBBBBKKBWBBK',
      '.......KKBBBBBBBBBBBBBBBBBBBBBK.',
      '.........KKKKKKKKKKKKKKKKKKKKK..',
      '............KBKBKBKWKWKWKBK.....',
      '.............KKKKKKKKKKKKK......',
      '............KK...KKKKKK..KK.....',
      '...........KBWKKKKBBWBKKKBWK....',
      '...........KBWKBKKKKKKKKBKWK....',
      '...........KBWKKKKKWWWWKKKWK....',
      '...........KBWK.KKWWWWWKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWKBBBKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWWWWWKKBWK....',
      '...........KBWKKKKKKKKKKKBWK....',
      '...........KBWKKKBBBWWWKKKWK....',
      '...........KKKKBBBBBBBWWBKKK....',
      '............KBBBBBBBBBBWBBBK....',
      '...........KKKKKKKKKKKKKKKKKK...',
      '..........KBBBBBBBBBBBWWWWWBBK..',
      '..........KKKKKKKKKKKKKKKKKKKK..',
    ],
  },
  bigEye1: {
    ox: 16,
    oy: 38,
    rows: [
      '......KKKKKKK............KKKK...',
      '.....KBBBBBBBK..........KBBBBK..',
      '....KBBBWWWBKKKKKKKKKKKKKKWBKKK.',
      '...KBBBBBBBKKBKKBBBBBBKKKBBKKBKK',
      '...KBBBBBBBKKBWBBBBBBBBBKKBKKBWK',
      '...KBBBBBBBKKBKBBBBBBBBBBKBKKBKK',
      '..KKBBBBBBBBKKKKBBBBBBBBBKBBKKK.',
      '.KWBKBBBBBBBBKKKKBBBBBBBBBKBBKK.',
      'KWBK.KKKKKKKKKKKKKBBBBBBKKBKKKK.',
      'KWK...KKBWKKKKKKBBKKKKKKBKKBKKWK',
      'KWK....KBBWKBKKBKBBBBBBBWKKBBKWK',
      'KWK....KKKKKBBKKKKBBBBBBKWKKBKWK',
      'KWK....KBBBBBBBKKKKKKKKKKWKKBBK.',
      'KBWKKKKKKBBBBBBBKKKKKKKKKKKKBBK.',
      '.KBWWWWBKKBBBBBBBKKKKKKKKKKBBWBK',
      '..KKBBBBKKBBBBBBBBBKKKKKKKBBBWBK',
      '....KKKKKBBBBBBBBBBBBBBBBBBBBWBK',
      '......KBBBBBBBBBBKWBBBBBBKWBWWBK',
      '......KBBBBBBBBBBKKBBBBBBKKBWBBK',
      '.......KKBBBBBBBBBBBBBBBBBBBBBK.',
      '.........KKKKKKKKKKKKKKKKKKKKK..',
      '............KBKBKBKWKWKWKBK.....',
      '............KKKKKKKKKKKKKKK.....',
      '...........KBWKKKKBBWBKKKBWK....',
      '...........KBWKBKKKKKKKKBKWK....',
      '...........KBWKKKKKWWWWKKKWK....',
      '...........KBWK.KKWWWWWKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWKBBBKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWWWWWKKBWK....',
      '...........KBWKKKKKKKKKKKBWK....',
      '...........KBWKKKBBBWWWKKKWK....',
      '...........KKKKBBBBBBBWWBKKK....',
      '............KBBBBBBBBBBWBBBK....',
      '...........KKKKKKKKKKKKKKKKKK...',
      '..........KBBBBBBBBBBBWWWWWBBK..',
      '..........KKKKKKKKKKKKKKKKKKKK..',
    ],
  },
  bigEye2: {
    ox: 16,
    oy: 48,
    rows: [
      '................KKKKKK..........',
      '......KKKKKKK.KKBBBBBBKKKKKKK...',
      '.....KBBBBBBBKBBBBBBBBBBKBBBBK..',
      '....KBBBWWWBKKKBBBBKKKKKBKWBKKK.',
      '...KBBBBBBBKKBKKBKKWWWWWKBBKKBKK',
      '...KBBBBBBBKKBWKKWWWWKKWWKBKKBWK',
      '...KBBBBBBBKKBKKWWWWKBWKWKBKKBKK',
      '..KKBBBBBBBBKKKKWWWWKBBKWKBBKKK.',
      '.KWBKBBBBBBBBKKBKWWWWKKWKBKBBK..',
      'KWBK.KKKKKKKKKKKKKWWWWWWKKBKKWK.',
      'KWK...KKBWKKKKKKKKKKKKKKKKKBKKWK',
      'KWK....KBBWKBKKKKKKKKKKKWKKBBKWK',
      'KWK....KKKKKBBKKKKKKKKKKKWKKBKWK',
      'KWK....KBBBBBBBKKKKKKKKKKWKKBBK.',
      'KBWKKKKKKBBBBBBBKKKKKKKKKKKKBBK.',
      '.KBWWWWBKKBBBBBBBKKKKKKKKKKBBWBK',
      '..KKBBBBKKBBBBBBBBBKKKKKKKBBBWBK',
      '....KKKKKBBBBBBBBBBBBBBBBBBBBWBK',
      '......KBBBBBBBBBBKWBBBBBBKWBWWBK',
      '......KBBBBBBBBBBKKBBBBBBKKBWBBK',
      '.......KKBBBBBBBBBBBBBBBBBBBBBK.',
      '.........KKKKKKKKKKKKKKKKKKKKK..',
      '............KBKBKBKWKWKWKBK.....',
      '.............KKKKKKKKKKKKK......',
      '..................KKKK..........',
      '..................KKWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '............KK...KKKKKK..KK.....',
      '...........KBWKKKKBBWBKKKBWK....',
      '...........KBWKBKKKKKKKKBKWK....',
      '...........KBWKKKKKWWWWKKKWK....',
      '...........KBWK.KKWWWWWKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWKBBBKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWWWWWKKBWK....',
      '...........KBWKKKKKKKKKKKBWK....',
      '...........KBWKKKBBBWWWKKKWK....',
      '...........KKKKBBBBBBBWWBKKK....',
      '............KBBBBBBBBBBWBBBK....',
      '...........KKKKKKKKKKKKKKKKKK...',
      '..........KBBBBBBBBBBBWWWWWBBK..',
      '..........KKKKKKKKKKKKKKKKKKKK..',
    ],
  },
  bigEye3: {
    ox: 16,
    oy: 48,
    rows: [
      '................KKKKKK..........',
      '......KKKKKKK.KKBBBBBBKKKKKKK...',
      '.....KBBBBBBBKBBBBBBBBBBKBBBBK..',
      '....KBBBWWWBKKKBBBBKKKKKBKWBKKK.',
      '...KBBBBBBBKKBKKBKKWWKKWKBBKKBKK',
      '...KBBBBBBBKKBWKKWWWKBWKWKBKKBWK',
      '...KBBBBBBBKKBKKWWWWKBBKWKBKKBKK',
      '..KKBBBBBBBBKKKKWWWWWKKWWKBBKKK.',
      '.KWBKBBBBBBBBKKBKWWWWWWWKBKBBK..',
      'KWBK.KKKKKKKKKKKKKWWWWWWKKBKKWK.',
      'KWK...KKBWKKKKKKKKKKKKKKKKKBKKWK',
      'KWK....KBBWKBKKKKKKKKKKKWKKBBKWK',
      'KWK....KKKKKBBKKKKKKKKKKKWKKBKWK',
      'KWK....KBBBBBBBKKKKKKKKKKWKKBBK.',
      'KBWKKKKKKBBBBBBBKKKKKKKKKKKKBBK.',
      '.KBWWWWBKKBBBBBBBKKKKKKKKKKBBWBK',
      '..KKBBBBKKBBBBBBBBBKKKKKKKBBBWBK',
      '....KKKKKBBBBBBBBBBBBBBBBBBBBWBK',
      '......KBBBBBBBBBBKWBBBBBBKWBWWBK',
      '......KBBBBBBBBBBKKBBBBBBKKBWBBK',
      '.......KKBBBBBBBBBBBBBBBBBBBBBK.',
      '.........KKKKKKKKKKKKKKKKKKKKK..',
      '............KBKBKBKWKWKWKBK.....',
      '.............KKKKKKKKKKKKK......',
      '..................KKKK..........',
      '..................KKWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '............KK...KKKKKK..KK.....',
      '...........KBWKKKKBBWBKKKBWK....',
      '...........KBWKBKKKKKKKKBKWK....',
      '...........KBWKKKKKWWWWKKKWK....',
      '...........KBWK.KKWWWWWKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWKBBBKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWWWWWKKBWK....',
      '...........KBWKKKKKKKKKKKBWK....',
      '...........KBWKKKBBBWWWKKKWK....',
      '...........KKKKBBBBBBBWWBKKK....',
      '............KBBBBBBBBBBWBBBK....',
      '...........KKKKKKKKKKKKKKKKKK...',
      '..........KBBBBBBBBBBBWWWWWBBK..',
      '..........KKKKKKKKKKKKKKKKKKKK..',
    ],
  },
  bigEye4: {
    ox: 16,
    oy: 44,
    rows: [
      '................KKKKKK..........',
      '......KKKKKKK.KKBBBBBBKKKKKKK...',
      '.....KBBBBBBBKBBBBBBBBBBKBBBBK..',
      '....KBBBWWWBKKKBBBBKKKKKBKWBKKK.',
      '...KBBBBBBBKKBKKBKKWWWWWKBBKKBKK',
      '...KBBBBBBBKKBWKKWWWWKKWWKBKKBWK',
      '...KBBBBBBBKKBKKWWWWKBWKWKBKKBKK',
      '..KKBBBBBBBBKKKKWWWWKBBKWKBBKKK.',
      '.KWBKBBBBBBBBKKBKWWWWKKWKBKBBK..',
      'KWBK.KKKKKKKKKKKKKWWWWWWKKBKKWK.',
      'KWK...KKBWKKKKKKKKKKKKKKKKKBKKWK',
      'KWK....KBBWKBKKKKKKKKKKKWKKBBKWK',
      'KWK....KKKKKBBKKKKKKKKKKKWKKBKWK',
      'KWK....KBBBBBBBKKKKKKKKKKWKKBBK.',
      'KBWKKKKKKBBBBBBBKKKKKKKKKKKKBBK.',
      '.KBWWWWBKKBBBBBBBKKKKKKKKKKBBWBK',
      '..KKBBBBKKBBBBBBBBBKKKKKKKBBBWBK',
      '....KKKKKBBBBBBBBBBBBBBBBBBBBWBK',
      '......KBBBBBBBBBBKWBBBBBBKWBWWBK',
      '......KBBBBBBBBBBKKBBBBBBKKBWBBK',
      '.......KKBBBBBBBBBBBBBBBBBBBBBK.',
      '.........KKKKKKKKKKKKKKKKKKKKK..',
      '............KBKBKBKWKWKWKBK.....',
      '.............KKKKKKKKKKKKK......',
      '..................KKKK..........',
      '..................KKWK..........',
      '..................KWWK..........',
      '..................KWWK..........',
      '............KK...KKKKKK..KK.....',
      '...........KBWKKKKBBWBKKKBWK....',
      '...........KBWKBKKKKKKKKBKWK....',
      '...........KBWKKKKKWWWWKKKWK....',
      '...........KBWK.KKWWWWWKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWKBBBKKBWK....',
      '...........KBWK.KWWKKKKKKBWK....',
      '...........KBWK.KWWWWWWKKBWK....',
      '...........KBWKKKKKKKKKKKBWK....',
      '...........KBWKKKBBBWWWKKKWK....',
      '...........KKKKBBBBBBBWWBKKK....',
      '............KBBBBBBBBBBWBBBK....',
      '...........KKKKKKKKKKKKKKKKKK...',
      '..........KBBBBBBBBBBBWWWWWBBK..',
      '..........KKKKKKKKKKKKKKKKKKKK..',
    ],
  },
  blader1: {
    ox: 8,
    oy: 20,
    rows: [
      '.......KK.......',
      'WWWWWWWhhK......',
      'KKKKKKKhhK......',
      '......KWWK......',
      '.....KKKKKK.....',
      '...KKhhhhhhKK...',
      '..KhhhhhhhhhhK..',
      '.KhhhhhhhhhhhhK.',
      '.KhhhhhhhhhhhhK.',
      'KhhWWWhhhWWWhhhK',
      'KhWWWWWhWWWWWhhK',
      'KhWWWWWhWWWWWhhK',
      'KhWKKWWhKKWWWhhK',
      'KKhKKWWhKKWWhhKK',
      'KWKKhhhhhhhhKKWK',
      'KWKWKKKKKKKKWKWK',
      'KWKWKWWKWWKWWKWK',
      '.KKWKWWKWWKWWKK.',
      '..KKKWWKWWKWKK..',
      '....KKKKKKKK....',
    ],
  },
  blader2: {
    ox: 8,
    oy: 20,
    rows: [
      '.......KK.......',
      '......KhhWWWWWWW',
      '......KhhKKKKKKK',
      '......KWWK......',
      '.....KKKKKK.....',
      '...KKhhhhhhKK...',
      '..KhhhhhhhhhhK..',
      '.KhhhhhhhhhhhhK.',
      '.KhhhhhhhhhhhhK.',
      'KhhWWWhhhWWWhhhK',
      'KhWWWWWhWWWWWhhK',
      'KhWWWWWhWWWWWhhK',
      'KhWKKWWhKKWWWhhK',
      'KKhKKWWhKKWWhhKK',
      'KWKKhhhhhhhhKKWK',
      'KWKWKKKKKKKKWKWK',
      'KWKWKWWKWWKWWKWK',
      '.KKWKWWKWWKWWKK.',
      '..KKKWWKWWKWKK..',
      '....KKKKKKKK....',
    ],
  },
  picketMan0: {
    ox: 16,
    oy: 24,
    rows: [
      '..............KKKKKK.............',
      '.............KOOOOOOK............',
      '............KOOOOOOKKK...........',
      '...........KOOOOOOKOWWK.KKKKKK...',
      '...........KKKKKKOKOWWKKKOOKKOK..',
      '...KKKK...KKOOOOOOOKKKKOKKOOKKOK.',
      '..KKK.....KOOOOOOOOOOOKOOKKOOKKK.',
      '.KKK.......KKKKKKKKKKKKKOOKKOOKK.',
      'KKKOK......KWKWWKKWKKWKKKOOKKOOK.',
      'KKKOK......KWKWWKKWKKWKOKKOOKKOK.',
      'KK.KOK.....KWKKWWWKWWKKOOKKOOKKK.',
      'K..KOK....KKKKKKKKKKKKKKOOKKOOKK.',
      'K...KOK..KWWKKKKKKWKKKKKKOOKKOOK.',
      '....KOKKKWWWKOKKKKKKKOKOKKOOKKOK.',
      '.....KKOOKWWKOOOOOOOOOKOOKKOOKKK.',
      '.....KOKOKWKKOOOOOOOOOOKOOKKOOKK.',
      '.....KOOOOK..KOOOOOOOOOOKOOKKOK..',
      '......KOOK..KKKKOOOOOOOOKKOOKK...',
      '.......KK..KWWWWKOOOOOOKWWKKK....',
      '..........KWWWWWWKKKKKKWWWWK.....',
      '..........KKKWWKK.....KWWWKK.....',
      '..........KKKKK........KKKKKK....',
      '........KKKKKKKK.......KKKKKKKK..',
      '........KKKKKKKK.......KKKKKKKK..',
    ],
  },
  picketMan1: {
    ox: 16,
    oy: 24,
    rows: [
      '.................KKKKKK..........',
      '...........KKK..KOOOOOOKKK.......',
      '..........KOOOK.KOOOOOKKKOK......',
      '..........KOOOKKOOOOOKOWWKOK.....',
      '.........KKOOOWKKKKKOKOWWKOK.....',
      '....K...KOKOOWWKOOOOOOKKKKOK.....',
      '....K..KOOKKKWWWKOOOOOOOOOKK.....',
      '....KKKOOK..KWWWKKKKKKKKKKKK.....',
      '....KKOOK...KWWWKKWKKWKKWKOK.....',
      '....KKKK.....KWWWKWKKWKKWKOK.....',
      '.....KKK.....KWWWKKWWKWWKKOK.....',
      '......KKKK...KWWWKKKKKKKKKOK.....',
      '.............KWWWKKKKWKKKKOK.....',
      '..............KWWKKKKKKOKKOK.....',
      '..............KKKOOOOOOOKKOK.....',
      '...............KOOOOOOOOKOOK.....',
      '..............KOOOOOOOOOKOK......',
      '..............KKOOOOOOOKKK.......',
      '.............KWWKOOOOOKWWK.......',
      '............KWWWWKKKKKWWWKK......',
      '...........KKKWWK.....KWKKKK.....',
      '..........KKKKKK......KKKKKK.....',
      '........KKKKKKKK......KKKKKKKK...',
      '........KKKKKKKK......KKKKKKKK...',
    ],
  },
  picketMan2: {
    ox: 16,
    oy: 24,
    rows: [
      '................KKKKKKKK.........',
      '...............KOOOOOOOOK........',
      '..............KOOKKKKKKOOK.......',
      '..............KOKKKKKKKKKKKKK....',
      '..............KOKKKOOKKOOOOOOK...',
      '..............KOKKWOOKOOOOOOKKK..',
      '..............KOKWWWKOOOOOOKOWWK.',
      '..............KOKWWWKKKKKKOKOWWK.',
      '..............KOKKWKKOOOOOOOKKKK.',
      '..............KOKKKKOOOOOOOOOOOOK',
      '..............KOKKOKKKKKKKKKKKKKK',
      '..............KKKOOOKKKWWKKWKKWK.',
      '..............KKOOOOOKKWWKKWKKWK.',
      '............KKKKOOOOKWWKKWWKWWKK.',
      '...........KKKKKOOOOKWWWWKKKKKKK.',
      '..........KKKKWKOOOOKWWWWWWKKKK..',
      '..........KKKWWWKOOOOKWWWWWWWKKK.',
      '..........KKKWWWWKOOOOKKWWWWOOOOK',
      '..........KKKWWWK.KOOOOOKKWOOOOOK',
      '...........KKKKK...KKKKKWWKKKOOOK',
      '........................KKKK.KKK.',
      '.......................KKKKK.....',
      '......................KKKKKKK....',
      '......................KKKKKKKK...',
    ],
  },
  picket0: {
    ox: 6,
    oy: 6,
    rows: [
      '......KOK....',
      '.....KKKKK...',
      '...KKKKKKKKK.',
      '..KK..KOK..KK',
      '......KOK....',
      '......KOK....',
      '......KOK....',
      '......KOK....',
      '......KOK....',
      '......KOK....',
      '......KOK....',
      '......KKK....',
    ],
  },
  picket1: {
    ox: 6,
    oy: 6,
    rows: [
      '.........K...',
      '.........KK..',
      '..........K..',
      '..........KK.',
      '.KKKKKKKKKKKK',
      '.KOOOOOOOOKKO',
      '.KKKKKKKKKKKK',
      '..........KK.',
      '..........K..',
      '.........KK..',
      '.........K...',
      '.............',
    ],
  },
  picket2: {
    ox: 6,
    oy: 6,
    rows: [
      '.....KKK.....',
      '.....KOK.....',
      '.....KOK.....',
      '.....KOK.....',
      '.....KOK.....',
      '.....KOK.....',
      '.....KOK.....',
      '.....KOK.....',
      '.KK..KOK..KK.',
      '..KKKKKKKKK..',
      '....KKKKK....',
      '.....KOK.....',
    ],
  },
  picket3: {
    ox: 6,
    oy: 6,
    rows: [
      '...K.........',
      '..KK.........',
      '..K..........',
      '.KK..........',
      'KKKKKKKKKKKK.',
      'OKKOOOOOOOOK.',
      'KKKKKKKKKKKK.',
      '.KK..........',
      '..K..........',
      '..KK.........',
      '...K.........',
      '.............',
    ],
  },
  peng1: {
    ox: 12,
    oy: 8,
    rows: [
      '.........KKKKKKKKK......',
      '.......KKKKKWWKKKKKKKKK.',
      '......KKKKKKKKKKKKKKKKK.',
      '.....KKWWWKKKKKKKKKKKK..',
      '..KKKKWWWKKWKKKKKKKKK...',
      '.KLLKKWKKKWWKKKKKKKKKK..',
      'KLWLKKKKKWWWKKKKKKKKKKK.',
      'KLLLKKWKKWWKKKWKKKKKKKKK',
      '.KLLKKKWWWKKKWWWKKKKKKKK',
      '..WKKKKKKKKKWWWWWWKKKKK.',
      '..WK.KKKKKWWWWWWWLLLK...',
      '..WK..KWWWWWWWWWKKLLLK..',
      '..WK...KKWWWWWWKLLKLLK..',
      '..WK.....KKKKKKKKLLKK...',
      '.................KK.....',
    ],
  },
  peng2: {
    ox: 12,
    oy: 8,
    rows: [
      '..WK.....KKKKKKKKK......',
      '..WK...KKKKKWWKKKKKKKKK.',
      '..WK..KKKKKKKKKKKKKKKKK.',
      '..WK.KKWWWKKKKKKKKKKKK..',
      '..WKKKWWWKKWKKKKKKKKK...',
      '.KLLKKWKKKWWKKKKKKKKKK..',
      'KLWLKKKKKWWWKKKKKKKKKKK.',
      'KLLLKKWKKWWKKKWKKKKKKKKK',
      '.KLLKKKWWWKKKWWWKKKKKKKK',
      '..KKKKKKKKKKWWWWWWKKKKK.',
      '.....KKKKKWWWWWWWLLLK...',
      '......KWWWWWWWWWKKLLLK..',
      '.......KKWWWWWWKLLKLLK..',
      '.........KKKKKKKKLLKK...',
      '.................KK.....',
    ],
  },
  flea1: {
    ox: 7,
    oy: 10,
    rows: [
      '...KKKKKKKK...',
      '.KKKppppppKKK.',
      'KWpKpWWWWpKpWK',
      'KpKppppppppKpK',
      'KKppppppppppKK',
      'KppppppppppppK',
      'KpppKKKKKKpppK',
      '.KKKppKKppKKK.',
      '.KpppKppKpppK.',
      '.KKKK.KK.KKKK.',
    ],
  },
  flea2: {
    ox: 7,
    oy: 19,
    rows: [
      '...KKKKKKKK...',
      '.KKKppppppKKK.',
      'KWpKpWWWWpKpWK',
      'KpKppppppppKpK',
      'KKppppppppppKK',
      'KppppppppppppK',
      'KpppKKKKKKpppK',
      '.KKKKKKWpKKKK.',
      '....KpWKK.....',
      '.....KKWpK....',
      '....KpWKK.....',
      '....KKKWpK....',
      '...KKpWKKpK...',
      '...KppKKppK...',
      '...KppKKppK...',
      '...KppKKppK...',
      '....KpKKpK....',
      '....KpKKpK....',
      '.....K..K.....',
    ],
  },
  joeShield: {
    ox: 13,
    oy: 24,
    rows: [
      '...........KKKK...........',
      '.........KKhhhhKK.........',
      '........KhhhhhhhhK........',
      '..KKKK.KhhWhhhhhhhK.......',
      '.KhhhhKKhWWhhhhhhhK.......',
      'KhhhhhhKhhhhhhhhhhK.......',
      'KWWWWhhKKKKKKKKKKhKK......',
      'KWWWWWhKKKWhKKKKKhKKKK....',
      'KWWWWWhKKKhhKKKKhKKKKKK...',
      'KWWWWWhKhKKKKKKhhKKKKKK...',
      'KWWWWWhKhhhhhhhhKhKKKKKK..',
      'KWWWWWhKKhhhhhhKhhhKKKKKK.',
      'KWWWWWhKhKKKKKKhhhhKKKWWK.',
      'KWWWWWhKKhhhhhhhhhK.KWWWWK',
      'KWWWWWhKKhhhhhhhhK..KWWKWK',
      'KWWWWWhKKKWWWKKKK...KWWKWK',
      'KWWWWWhKKKWWWKKKKK..KWWKWK',
      'KhhhhhKhhhhhhhhhhhK..KWWK.',
      '.KhhhKhhhhhhhhhhhhhK..KKK.',
      '..KKKhhhhhKKKKKhhKKK..KWK.',
      '...KKKhhhK.....KKKKK..KKK.',
      '.KKKKKKKK......KKKKK......',
      'KKKKKKKKK.....KKKKKKKK....',
      'KKKKKKKK......KKKKKKKK....',
    ],
  },
  joeLower: {
    ox: 10,
    oy: 24,
    rows: [
      '..KK..KKKK..........',
      '.KWWKKhhhhKK........',
      'KWWKhhhhhhhhK.......',
      'KWKhhWhhhhhhhK......',
      'KWKhWWhhhhhhhK......',
      'KWKhhhhhhhhhhK......',
      'KWKKKKKKKKKKhK......',
      'KWKKKWhKKKKKhK......',
      'KWKKKhhKKKKhhKK.....',
      'KWKhKKKKKKhhKKKK....',
      'KWKhhhhhhhhKhKKK....',
      'KWKKhhhhhhKhKKKK....',
      'KWKhKKKKKKKKKKKK....',
      'KWWKhhhKWWWWKKKK....',
      'KWWKhKKWWWWWWKK.....',
      '.KWKKWKWWKKKWK......',
      '..KKKKKWWWWWWK......',
      '..KhhhhKWWWWKK......',
      '.KhhhhhhKKKKhhK.....',
      'KKhhhKKKKKhhhKKK....',
      'KKKhK.....KhKKKK....',
      'KKKKK......KKKKKK...',
      'KKKKK......KKKKKKKK.',
      'KKKKK......KKKKKKKK.',
    ],
  },
  joeShoot: {
    ox: 12,
    oy: 24,
    rows: [
      '.......KKKK..KKK.......',
      '.....KKhhhhKKWWWK......',
      '....KhhhhhhhhKWWWK.....',
      '...KhhWhhhhhhhKWWK.....',
      '...KhWWhhhhhhhKWWK.....',
      '...KhhhhhhhhhhKWWK.....',
      '...KKKKKKKKKKhKWWK.....',
      '...KKKWhKKKKKhKWWK.....',
      '...KKKhhKKKKhhKWWK.....',
      '...KhKKKKKKhhhKWWK.....',
      '...KhhhhhhhhKKKKWK.....',
      '..KKKKKKKhhKKKKKWK.....',
      'KKKKWWWWWKKKKKKKWK.....',
      'KWKWWWWWWWKKKKKWWK.....',
      'KKKWWKKKWWWKKKKWWK.....',
      '...KWWWWWWWKKKWWK......',
      '....KWWWWKKKhhKK.......',
      '...KhKKKKKhhhhhK.......',
      '..KhhhhhhhhhhhhhK......',
      '..KKhhhKKKKKhhhKKK.....',
      '..KKKKK.....KhKKKKK....',
      '.KKKKKK......KKKKKKK...',
      'KKKKKKKK......KKKKKKKK.',
      'KKKKKKKK......KKKKKKKK.',
    ],
  },
  joeJump: {
    ox: 14,
    oy: 31,
    rows: [
      '.........KKKK...............',
      '.......KKhhhhKK.............',
      '......KhhhhhhhhK............',
      '.....KhhWhhhhhhhK...........',
      '.....KhWWhhhhhhhK...........',
      '..KKKKhhhhhhhhhhK....KKKK...',
      '.KhhhhKKKKKKKKKhK..KKWWWWKKK',
      'KhhhhhhKWhKKKKKhKKKKWKKKWKWK',
      'KWWWWhhKhhKKKKhhKKKKWWWWWKKK',
      'KWWWWWhKKKKKKhhKKKKKKWWWK...',
      'KWWWWWhKhhhhhhKhKKKKKKKK....',
      'KWWWWWhKhhhhhKhhKKK.........',
      'KWWWWWhKKKKKKhhhhK..........',
      'KWWWWWhKhhhhhhhhK...........',
      'KWWWWWhKhhhhhhhK............',
      'KWWWWWhKWWWKKKKK............',
      'KWWWWWhKWWWKKKKK............',
      'KWWWWWhKhhhhhhhK............',
      'KWWWWWhKhhhhhhhK............',
      'KhhhhhKKKKKhhhhK............',
      '.KhhhKKKK..KhhhK............',
      '..KKKKKKKK.KhhhK............',
      '....KKKKKK.KhhhK............',
      '.....KKKKK.KhhKK............',
      '.....KKKK..KKKKK............',
      '.....KKK...KKKKK............',
      '...........KKKKK............',
      '...........KKKKK............',
      '...........KKKKK............',
      '...........KKKK.............',
      '...........KKK..............',
    ],
  },
  joeShot: {
    ox: 3,
    oy: 3,
    rows: [
      '..hh..',
      '.hWWh.',
      'hWWWWh',
      'hWWWWh',
      '.hWWh.',
      '..hh..',
    ],
  },
};

const selectArtOriginals = {
  megaSelect0: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqKWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqKWKWWWKQQKWKWWWWqKKQBBBK',
      'KWBBQKqWKKKWWWKQQKKKWWWWWqKQBBWK',
      'KWWBQKqWKKKWWWWQQKKKWWWWWqKQBWWK',
      'KWWBQKqWKKKWWWWQQKKKWWWWWqKQBWWK',
      'KBWBQKqWWKWWWWWSSWKWWWWWWqKQBWBK',
      'KBWBQKqWWWWWWWWSSWWWWWWWWqKQBWBK',
      'KBBBQKqWWWWWWWWSSWWWWWWWWqKQBBBK',
      'KKBBQKqqWWWWWWSSSSWWWWWWqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect1: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWKKQQQQKKWWWqqKQQQBBK',
      'KBBBQQKqWWWKWKKQQKKWKWWWqKKQBBBK',
      'KWBBQKqWWWWKKKKQQKKKKWWWWqKQBBWK',
      'KWWBQKqWWWWKKKWQQWKKKWWWWqKQBWWK',
      'KWWBQKqWWWWKKKWQQWKKKWWWWqKQBWWK',
      'KBWBQKqWWWWWKWWSSWWKWWWWWqKQBWBK',
      'KBWBQKqWWWWWWWWSSWWWWWWWWqKQBWBK',
      'KBBBQKqWWWWWWWWSSWWWWWWWWqKQBBBK',
      'KKBBQKqqWWWWWWSSSSWWWWWWqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect2: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWKqqKQQQBBK',
      'KBBBQQKqWWWWKWKQQKWWWKWKqKKQBBBK',
      'KWBBQKqWWWWWKKKQQKWWWKKKWqKQBBWK',
      'KWWBQKqWWWWWKKKQQWWWWKKKWqKQBWWK',
      'KWWBQKqWWWWWKKKQQWWWWKKKWqKQBWWK',
      'KBWBQKqWWWWWWKWSSWWWWWKWWqKQBWBK',
      'KBWBQKqWWWWWWWWSSWWWWWWWWqKQBWBK',
      'KBBBQKqWWWWWWWWSSWWWWWWWWqKQBBBK',
      'KKBBQKqqWWWWWWSSSSWWWWWWqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect3: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqWWWWWWKQQKWWWWWWqKKQBBBK',
      'KWBBQKqWWWWWWKKQQKWWWWWKWqKQBBWK',
      'KWWBQKqWWWWWKWKQQWWWWWKWKqKQBWWK',
      'KWWBQKqWWWWWKKKQQWWWWWKKKqKQBWWK',
      'KBWBQKqWWWWWKKKSSWWWWWKKKqKQBWBK',
      'KBWBQKqWWWWWKKKSSWWWWWKKKqKQBWBK',
      'KBBBQKqWWWWWWKWSSWWWWWWKWqKQBBBK',
      'KKBBQKqqWWWWWWSSSSWWWWWWqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect4: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqWWWWWWKQQKWWWWWWqKKQBBBK',
      'KWBBQKqWWWWWWWKQQKWWWWWWWqKQBBWK',
      'KWWBQKqWWWWWWWWQQWWWWWWWWqKQBWWK',
      'KWWBQKqWWWWWWKWQQWWWWWKWWqKQBWWK',
      'KBWBQKqWWWWWKWKSSWWWWKWKWqKQBWBK',
      'KBWBQKqWWWWWKKKSSWWWWKKKWqKQBWBK',
      'KBBBQKqWWWWWKKKSSWWWWKKKWqKQBBBK',
      'KKBBQKqqWWWWKKSSSSWWWKKKqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWKqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect5: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqWWWWWWKQQKWWWWWWqKKQBBBK',
      'KWBBQKqWWWWWWWKQQKWWWWWWWqKQBBWK',
      'KWWBQKqWWWWWWWWQQWWWWWWWWqKQBWWK',
      'KWWBQKqWWWWWKWWQQWWKWWWWWqKQBWWK',
      'KBWBQKqWWWWKWKWSSWKWKWWWWqKQBWBK',
      'KBWBQKqWWWWKKKWSSWKKKWWWWqKQBWBK',
      'KBBBQKqWWWWKKKWSSWKKKWWWWqKQBBBK',
      'KKBBQKqqWWWKKKSSSSKKKWWWqqKQBBKK',
      'KKKBQQKqqWWWKSSSSSSKWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect6: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqWWWWWWKQQKWWWWWWqKKQBBBK',
      'KWBBQKqWWWWWWWKQQKWWWWWWWqKQBBWK',
      'KWWBQKqWWWWWWWWQQWWWWWWWWqKQBWWK',
      'KWWBQKqWWKWWWWWQQWKWWWWWWqKQBWWK',
      'KBWBQKqWKWKWWWWSSKWKWWWWWqKQBWBK',
      'KBWBQKqWKKKWWWWSSKKKWWWWWqKQBWBK',
      'KBBBQKqWKKKWWWWSSKKKWWWWWqKQBBBK',
      'KKBBQKqqKKKWWWSSSSKKWWWWqqKQBBKK',
      'KKKBQQKqqKWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect7: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqWWWWWWKQQKWWWWWWqKKQBBBK',
      'KWBBQKqWKWWWWWKQQKKWWWWWWqKQBBWK',
      'KWWBQKqKWKWWWWWQQKWKWWWWWqKQBWWK',
      'KWWBQKqKKKWWWWWQQKKKWWWWWqKQBWWK',
      'KBWBQKqKKKWWWWWSSKKKWWWWWqKQBWBK',
      'KBWBQKqKKKWWWWWSSKKKWWWWWqKQBWBK',
      'KBBBQKqWKWWWWWWSSWKWWWWWWqKQBBBK',
      'KKBBQKqqWWWWWWSSSSWWWWWWqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  megaSelect8: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKBBBBKKKKKKKKKKKKKK',
      'KKKKKKKKKQQQQBWBBBBQQQKKKKKKKKKK',
      'KKKKKKKQQQQQQBWBBBBQQQQQKKKKKKKK',
      'KKKKKKQQQQQQQBBWWWBQQQQQQQKKKKKK',
      'KKKKKQQBBBQQQBBBBBBQQQQQQQQKKKKK',
      'KKKKQQBBBQQQQQBBBBQQQQQQQQQQKKKK',
      'KKKKQQBBQQQQQQQQQQQQQQQQQQQQKKKK',
      'KKKQQBBQQQQQQQBBBBQQQQQQQQQQQKKK',
      'KKKQQBQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKKQQQQQQQQQQBWBBBBQQQQQQQQQQKKK',
      'KKQQQQQQQQQQQBWBBBBQQQQQQQQQQQKK',
      'KKQQQQQQQQQQQBBWWWBQQQQQQQQQQQKK',
      'KKQQQQQQKKKKQQBBBBQQKKKKQQQQQQKK',
      'KKBQQQQKqqqqKQQQQQQKqqqqKQQQQBKK',
      'KBBQQQKqqWWWWKQQQQKWWWWqqKQQQBBK',
      'KBBBQQKqWWWWWWKQQKWWWWWWqKKQBBBK',
      'KWBBQKqWWWWWKWKQQKWKWWWWWqKQBBWK',
      'KWWBQKqWWWWKWKWQQWKWKWWWWqKQBWWK',
      'KWWBQKqWWWWKKKWQQWKKKWWWWqKQBWWK',
      'KBWBQKqWWWWKKKWSSWKKKWWWWqKQBWBK',
      'KBWBQKqWWWWKKKWSSWKKKWWWWqKQBWBK',
      'KBBBQKqWWWWWKWWSSWWKWWWWWqKQBBBK',
      'KKBBQKqqWWWWWWSSSSWWWWWWqqKQBBKK',
      'KKKBQQKqqWWWWSSSSSSWWWWqqKQQBKKK',
      'KKKKQQKSSSSSSSSKKSSSqqqqqKQQKKKK',
      'KKKKKQKSSSSSSSSqqSSSSSqqqKQKKKKK',
      'KKKKKQKqSSSSSSSSSSSSSSqqqKQKKKKK',
      'KKKKKKQKSSSSSSSKKKKqSqqqKQKKKKKK',
      'KKKKKKKQqSSSqKKKSSSKSqqqQKKKKKKK',
      'KKKKKKKKKqSSSSSqqqSqqqqKKKKKKKKK',
      'KKKKKKKKKKKqSSSSSSqqqKKKKKKKKKKK',
      'KKKKKKKKKKKKKKSSqqKKKKKKKKKKKKKK',
    ],
  },
  selectPanel0: {
    ox: 0,
    oy: 0,
    rows: [
      '..KKKKKKKKK.......KKKKKKKKKKKQ.......KKKKKKKKK..',
      '.KAAAAAAQKAKKKKKKKAKAAAAAAAQKAKKKKKKKAKAAAAAAAK.',
      'KAKKKKKKKKWQAAAAAAWKKKKKKKKKKWQAAAAAAWKKKKKKKKAK',
      'KAKWWWWAKKWAWWWWWWWKWWWWWWWAKWAWWWWWWWKWWWWWAKAK',
      'KAKAKKKKKKAQAAAAAAAKAKKKKKKKKAQAAAAAAAKAKKKKKKAK',
      'KAKKKKKKKKAKQQQQQQAKKKKKKKKKKAKQQQQQQAKKKKKKKKAK',
      'KAQQQQQQQKQKKKKKKKQKQQQQQQQQKQKKKKKKKQKQQQQQQQAK',
      'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      '.KAWAQKK................................KKAWAQK.',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQKK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      '.KAWAQKK................................KKAWAQK.',
      'KAWWWAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
      'KAAAAAAAQKAKKKKKKKAKAAAAAAAQKAKKKKKKKAKAAAAAAAAK',
      'KAKKKKKKKKWQAAAAAAWKKKKKKKKKKWQAAAAAAWKKKKKKKKAK',
      'KAKWWWWWKKWAWWWWWWWKWWWWWWWAKWAWWWWWWWKWWWWWWKAK',
      'KAKKKKKKKKAQAAAAAAAKAKKKKKKKKAQAAAAAAAKAKKKKKKAK',
      'KQKKKKKKKKAKQQQQQQAKKKKKKKKKKAKQQQQQQAKKKKKKKKQK',
      '.KQQQQQQQKQKKKKKKK.KQQQQQQQQKQKKKKKKKQKQQQQQQQK.',
      '..KKKKKKKKKK.......KKKKKKKKKKKK......KKKKKKKKK..',
    ],
  },
  selectPanel1: {
    ox: 0,
    oy: 0,
    rows: [
      '..KKKKKKKKK.......KKKKKKKKKKKQ.......KKKKKKKKK..',
      '.KSSSSSSSKAKKKKKKKAKSSSSSSSSKAKKKKKKKAKSSSSSSSK.',
      'KSWWWWWWWKWQAAAAAAWKWWWWWWWWKWQAAAAAAWKWWWWWWWSK',
      'KSWWWWWWWKWAWWWWWWWKWWWWWWWWKWAWWWWWWWKWWWWWWWSK',
      'KSWWWWWWWKAQAAAAAAAKWWWWWWWWKAQAAAAAAAKWWWWWWWSK',
      'KSWWWWWWWKAKQQQQQQAKWWWWWWWWKAKQQQQQQAKWWWWWWWSK',
      'KSSSSSSSSKQKKKKKKKQKSSSSSSSSKQKKKKKKKQKSSSSSSSSK',
      'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      '.KAWAQKK................................KKAWAQK.',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQK.',
      '.KAWAQKK................................KKAWAQKK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      '.KAWAQKK................................KKAWAQK.',
      'KAWWWAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKK................................KKKKKKKK',
      'KAWWAAQK................................KAWWAAQK',
      'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
      'KSSSSSSSSKAKKKKKKKAKSSSSSSSSKAKKKKKKKAKSSSSSSSSK',
      'KSWWWWWWWKWQAAAAAAWKWWWWWWWWKWQAAAAAAWKWWWWWWWSK',
      'KSWWWWWWWKWAWWWWWWWKWWWWWWWWKWAWWWWWWWKWWWWWWWSK',
      'KSWWWWWWWKAQAAAAAAAKWWWWWWWWKAQAAAAAAAKWWWWWWWSK',
      'KSWWWWWWWKAKQQQQQQAKWWWWWWWWKAKQQQQQQAKWWWWWWWSK',
      '.KSSSSSSSKQKKKKKKK.KSSSSSSSSKQKKKKKKKQKSSSSSSSK.',
      '..KKKKKKKKKK.......KKKKKKKKKKKK......KKKKKKKKK..',
    ],
  },
};

const tileArtOriginals = {
  tileDoor: {
    ox: 0,
    oy: 0,
    rows: [
      'KWWWWWWWWWWWWWGK',
      'KWGGGGDDDDGGGGDK',
      'KGDDDDKKKKDDDDDK',
      'KKKKKKKKKKKKKKKK',
      'KWWWWWWWWWWWWWGK',
      'KWGGGGDDDDGGGGDK',
      'KGDDDDKKKKDDDDDK',
      'KKKKKKKKKKKKKKKK',
      'KWWWWWWWWWWWWWGK',
      'KWGGGGDDDDGGGGDK',
      'KGDDDDKKKKDDDDDK',
      'KKKKKKKKKKKKKKKK',
      'KWWWWWWWWWWWWWGK',
      'KWGGGGDDDDGGGGDK',
      'KGDDDDKKKKDDDDDK',
      'KKKKKKKKKKKKKKKK',
    ],
  },
};

// INITIALIZATION

registerArt(megaArtOriginals, 'mega');
registerArt(selectArtOriginals, 'mega');
registerArt(effectArtOriginals, 'enemy');
registerArt(itemArtOriginals, 'enemy');
registerArt(enemyArtOriginals, 'enemy');
registerArt(tileArtOriginals, 'enemy');
