// VARIABLES

const brickRows = [
  'WWWWWWWGWWWWWWWG',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'GDDDDDDDGDDDDDDD',
  'WWWGWWWWWWWGWWWW',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'DDDGDDDDDDDGDDDD',
];

const tileArt = {
  tileBrick: { ox: 0, oy: 0, rows: brickRows },
  tileGrass: {
    ox: 0,
    oy: 0,
    rows: [
      'hhhhhhhhhhhhhhhh',
      'hhghhhhhhghhhhgh',
      'ggggghgggggghggg',
      'gegggggegggggegg',
      'eKeegeKeeegKeeKe',
      'K.KeeK.KeKe.KeK.',
      ...brickRows.slice(6).map((row, index) => (index === 0 ? row.replace(/./g, (ch, i) => (i % 5 === 1 ? 'K' : ch)) : row)),
    ],
  },
  tileGirder: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKKK',
      'OLLLLLLLLLLLLLLo',
      'OLOOOOOOOOOOOOOo',
      'OOWoOOOOOOOOWoOo',
      'OOooOOOOOOOOooOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOWoOOOOOOOOWoOo',
      'OOooOOOOOOOOooOo',
      'OoooooooooooooNo',
      'oNNNNNNNNNNNNNNN',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileLadder: {
    ox: 0,
    oy: 0,
    rows: [
      '...WGD....WGD...',
      '...WWWWWWWWGD...',
      '...WGGGGGGWGD...',
      '...WGDDDDDWGD...',
      '...WGD....WGD...',
      '...WGD....WGD...',
      '...WWWWWWWWGD...',
      '...WGGGGGGWGD...',
      '...WGDDDDDWGD...',
      '...WGD....WGD...',
      '...WGD....WGD...',
      '...WWWWWWWWGD...',
      '...WGGGGGGWGD...',
      '...WGDDDDDWGD...',
      '...WGD....WGD...',
      '...WGD....WGD...',
    ],
  },
  tileMesh: {
    ox: 0,
    oy: 0,
    rows: [
      'e......ee......e',
      '.e....e..e....e.',
      '..e..e....e..e..',
      '...ee......ee...',
      '...ee......ee...',
      '..e..e....e..e..',
      '.e....e..e....e.',
      'e......ee......e',
      'e......ee......e',
      '.e....e..e....e.',
      '..e..e....e..e..',
      '...ee......ee...',
      '...ee......ee...',
      '..e..e....e..e..',
      '.e....e..e....e.',
      'e......ee......e',
    ],
  },
  tilePillar: {
    ox: 0,
    oy: 0,
    rows: [
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KKKKKKKK....',
      '...KeggggeeeK...',
      '...KKKKKKKKKK...',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
    ],
  },
  tileBack: {
    ox: 0,
    oy: 0,
    rows: [
      'uuuuuuuKuuuuuuuK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'KKKKKKKKKKKKKKKK',
      'uuuKuuuuuuuKuuuu',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileBackTop: {
    ox: 0,
    oy: 0,
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      'KKKKKKKKKKKKKKKK',
      'uuuuuuuKuuuuuuuK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileMetal: {
    ox: 0,
    oy: 0,
    rows: [
      'WWWWWWWWWWWWWWWG',
      'WGGGGGGGGGGGGGGD',
      'WGWDGGGGGGGGWDGD',
      'WGDDGGGGGGGGDDGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGWDGGGGGGGGWDGD',
      'WGDDGGGGGGGGDDGD',
      'WGGGGGGGGGGGGGGD',
      'GDDDDDDDDDDDDDDD',
    ],
  },
};
