// VARIABLES

const brickRows = [
  'WWWWWWWGWWWWWWWG',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'WGGGGGGDWGGGGGGD',
  'GDDDDDDDGDDDDDDD',
  'WWWGWWWWWWWGWWWW',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'GGGDWGGGGGGDWGGG',
  'DDDGDDDDDDDGDDDD',
];

const iceRockRows = [
  'aaaaaaaaaaaaaaaK',
  'aAAAAAAAAAAAAABK',
  'aAAAWAAAAAAAAABK',
  'aAAAAAAAAAAAAABK',
  'aAAAAAAAAAWAAABK',
  'aAAAAAAAAAAAAABK',
  'aBBBBBBBBBBBBBBK',
  'KKKKKKKKKKKKKKKK',
  'aaaaaaKaaaaaaaaa',
  'AAAAABKaAAAAAAAA',
  'AAAAABKaAAAAAAAA',
  'AAWAABKaAAAAWAAA',
  'AAAAABKaAAAAAAAA',
  'AAAAABKaAAAAAAAA',
  'BBBBBBKaBBBBBBBB',
  'KKKKKKKKKKKKKKKK',
];

const pineTreeTier = [
  '....KWWWWWaK....',
  '...KWWaaeeeeK...',
  '..KWaeeeeeeeeK..',
  '..KeeeeeeeeeeK..',
  '.KeeeeeeeeeeeeK.',
  'KeeeeeeeeeeeeeeK',
  'KKKeKKeKKeKKeKKK',
  '...KWWWWWaaK....',
];

const tileArt = {
  tileBrick: { ox: 0, oy: 0, rows: brickRows },
  tileGrass: {
    ox: 0,
    oy: 0,
    rows: [
      'hhhhhhhhhhhhhhhh',
      'hhghhhhhhghhhhgh',
      'ggggghgggggghggg',
      'gegggggegggggegg',
      'eKeegeKeeegKeeKe',
      'K.KeeK.KeKe.KeK.',
      ...brickRows.slice(6).map((row, index) => (index === 0 ? row.replace(/./g, (ch, i) => (i % 5 === 1 ? 'K' : ch)) : row)),
    ],
  },
  tileGirder: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKKK',
      'OLLLLLLLLLLLLLLo',
      'OLOOOOOOOOOOOOOo',
      'OOWoOOOOOOOOWoOo',
      'OOooOOOOOOOOooOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOOOOOOOOOOOOOOo',
      'OOWoOOOOOOOOWoOo',
      'OOooOOOOOOOOooOo',
      'OoooooooooooooNo',
      'oNNNNNNNNNNNNNNN',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileLadder: {
    ox: 0,
    oy: 0,
    rows: [
      '...WGD....WGD...',
      '...WWWWWWWWGD...',
      '...WGGGGGGWGD...',
      '...WGDDDDDWGD...',
      '...WGD....WGD...',
      '...WGD....WGD...',
      '...WWWWWWWWGD...',
      '...WGGGGGGWGD...',
      '...WGDDDDDWGD...',
      '...WGD....WGD...',
      '...WGD....WGD...',
      '...WWWWWWWWGD...',
      '...WGGGGGGWGD...',
      '...WGDDDDDWGD...',
      '...WGD....WGD...',
      '...WGD....WGD...',
    ],
  },
  tileMesh: {
    ox: 0,
    oy: 0,
    rows: [
      'e......ee......e',
      '.e....e..e....e.',
      '..e..e....e..e..',
      '...ee......ee...',
      '...ee......ee...',
      '..e..e....e..e..',
      '.e....e..e....e.',
      'e......ee......e',
      'e......ee......e',
      '.e....e..e....e.',
      '..e..e....e..e..',
      '...ee......ee...',
      '...ee......ee...',
      '..e..e....e..e..',
      '.e....e..e....e.',
      'e......ee......e',
    ],
  },
  tilePillar: {
    ox: 0,
    oy: 0,
    rows: [
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KKKKKKKK....',
      '...KeggggeeeK...',
      '...KKKKKKKKKK...',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
      '....KegggeeK....',
    ],
  },
  tileBack: {
    ox: 0,
    oy: 0,
    rows: [
      'uuuuuuuKuuuuuuuK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'KKKKKKKKKKKKKKKK',
      'uuuKuuuuuuuKuuuu',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'vvvKuvvvvvvKuvvv',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileBackTop: {
    ox: 0,
    oy: 0,
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      'KKKKKKKKKKKKKKKK',
      'uuuuuuuKuuuuuuuK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'uvvvvvvKuvvvvvvK',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileIceRock: { ox: 0, oy: 0, rows: iceRockRows },
  tileSnow: {
    ox: 0,
    oy: 0,
    rows: [
      'WWWWWWWWWWWWWWWW',
      'WWWWWWWWWWWWWWWW',
      'WWWWWaWWWWWWWWWW',
      'aWWWaaaWWWWaWWWa',
      'aaWaaAaaWWaaaWaa',
      'KaaaKAaaaaaKaaaK',
      'aKaKBKaKKaKBKaKB',
      'KKKKKKKKKKKKKKKK',
      ...iceRockRows.slice(8),
    ],
  },
  tileIce: {
    ox: 0,
    oy: 0,
    rows: [
      'WWWWWWWWWWWWWWWa',
      'WaaaaaaaaaaaaaaA',
      'WaWWaaaaaaaaaaaA',
      'WaWaaaaaaaaaaaaA',
      'WaaaaaaaaaaaaaaA',
      'WaaaaaaaaaaaaaaA',
      'WaaaaaaaaaaaWaaA',
      'WaaaaaaaaaaWaaaA',
      'WaaaaaaaaaWaaaaA',
      'WaaaaaaaaWaaaaaA',
      'WaaaaaaaaaaaaaaA',
      'WaaaaaaaaaaaaaaA',
      'WaaaaaaaaaaaaWaA',
      'WaaaaaaaaaaaaaaA',
      'aAAAAAAAAAAAAAAA',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileLog: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKKK',
      'WWWWWWWWWWWWWWWW',
      'aWWWWaWWWWWWaWWW',
      'nannnnnannnnnnan',
      'OOOOOOOOOOOOOOOO',
      'nnOnnnnnnnOnnnnn',
      'nnnnnNnnnnnnnnnN',
      'nNnnnnnnnNnnnnnn',
      'nnnnNnnnnnnnNnnn',
      'nnnnnnnnNnnnnnnn',
      'NnnNnnnnnnnnnNnn',
      'nnnnnnnNnnnnnnnn',
      'NNnnnNNNNnnNNNNn',
      'NNNNNNNNNNNNNNNN',
      'KNNNNNNNNNNNNNNK',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileSpike: {
    ox: 0,
    oy: 0,
    rows: [
      '...WK......WK...',
      '...WK......WK...',
      '..WaAK....WaAK..',
      '..WaAK....WaAK..',
      '..WaAK....WaAK..',
      '.WaaAAK..WaaAAK.',
      '.WaaAAK..WaaAAK.',
      '.WaaAAK..WaaAAK.',
      'WaaaAAAKWaaaAAAK',
      'WaaaAAAKWaaaAAAK',
      'WaaaAAAKWaaaAAAK',
      'WaaaAAAKWaaaAAAK',
      'aaaaAAAAaaaaAAAA',
      'AAAAAAAAAAAAAAAA',
      'BBBBBBBBBBBBBBBB',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileCrystal: {
    ox: 0,
    oy: 0,
    rows: [
      'KKKKKKKKKKKKKKKK',
      'KKKQKKKKKKKKKKKK',
      'KKQQQKKKKKKKKQKK',
      'KQQaQQKKKKKKQQQK',
      'KKQQQKKKKKKQQaQQ',
      'KKKQKKKKKKKKQQQK',
      'KKKKKKKKKKKKKQKK',
      'KKKKKKKQKKKKKKKK',
      'KKKKKKQQQKKKKKKK',
      'KKKKKQQaQQKKKKKK',
      'KKKKKKQQQKKKKKKK',
      'KKKKKKKQKKKKKKKK',
      'KQKKKKKKKKKKKKQK',
      'QQQKKKKKKKKKKQQQ',
      'KQKKKKKKKKKKKKQK',
      'KKKKKKKKKKKKKKKK',
    ],
  },
  tileTreeTop: {
    ox: 0,
    oy: 0,
    rows: [
      '.......KK.......',
      '......KWWK......',
      '......KWaK......',
      '.....KWWaeK.....',
      '.....KaeeeK.....',
      '....KeeeeeeK....',
      '...KKeKeeKeKK...',
      '....KWWWWaaK....',
      ...pineTreeTier,
    ],
  },
  tileTree: { ox: 0, oy: 0, rows: [...pineTreeTier, ...pineTreeTier] },
  tileTrunk: {
    ox: 0,
    oy: 0,
    rows: [
      '...KWWaaeeeeK...',
      '..KWaeeeeeeeeK..',
      '.KeeeeeeeeeeeeK.',
      'KeeeeeeeeeeeeeeK',
      'KKKeKKeKKeKKeKKK',
      '......KNnK......',
      '......KNnK......',
      '......KNnK......',
      '......KNnK......',
      '......KNnK......',
      '......KNnK......',
      '......KNnK......',
      '.....KNNnnK.....',
      '....KNNNnnnK....',
      '....WWWWWWWW....',
      '..WWWWWWWWWWWW..',
    ],
  },
  tileMetal: {
    ox: 0,
    oy: 0,
    rows: [
      'WWWWWWWWWWWWWWWG',
      'WGGGGGGGGGGGGGGD',
      'WGWDGGGGGGGGWDGD',
      'WGDDGGGGGGGGDDGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGGGGGGGGGGGGGGD',
      'WGWDGGGGGGGGWDGD',
      'WGDDGGGGGGGGDDGD',
      'WGGGGGGGGGGGGGGD',
      'GDDDDDDDDDDDDDDD',
    ],
  },
};

const commonArt = {
  bubble: { ox: 2, oy: 2, rows: ['.WW.', 'W..W', 'W..W', '.WW.'] },
  splash0: {
    rows: [
      '......W..W......',
      '...W..W..W..W...',
      '....W.aWWa.W....',
      '..WWaaaaaaaaWW..',
    ],
  },
  splash1: {
    rows: [
      '....W......W....',
      '.....W....W.....',
      '..W...W..W...W..',
      '...W..aWWa..W...',
      '....aa.aa.aa....',
      '.WWaaaaaaaaaaWW.',
    ],
  },
  splash2: {
    rows: [
      '..W..........W..',
      '................',
      '.W....W..W....W.',
      '................',
      '...a..........a.',
      '..a.a..aa..a.a..',
    ],
  },
};

// INITIALIZATION

registerArt(tileArt, 'enemy');
registerArt(commonArt, 'enemy');
